export const codeExtra = [
  ["WebRTC","n","real-time audio, video, and data in the browser","ارتباط بلادرنگ در مرورگر","وب‌آرتی‌سی"],
  ["WebGL","n","a GPU drawing API in the browser","وب‌جی‌ال","وب‌جی‌ال"],
  ["WebGPU","n","a modern GPU API for the web","وب‌جی‌پی‌یو","وب‌جی‌پی‌یو"],
  ["Canvas 2D","n","the two-dimensional drawing context of canvas","بوم دوبعدی","کنوس دوبعدی"],
  ["OffscreenCanvas","n","a canvas that can be drawn on a worker","بوم خارج از صفحه","آف‌اسکرین"],
  ["service worker","n","a script that intercepts network requests","سرویس‌ورکر","سرویس‌ورکر"],
  ["PWA","n","a progressive web app that can install on a device","وب‌اپ پیش‌رونده","پی‌دبلیوای"],
  ["manifest","n","a JSON file describing an installable app","مانیفست","مانیفست"],
  ["push notification","n","a message a server sends to a device","اعلان فشاری","پوش نوتیف"],
  ["IndexedDB","n","a browser database for structured data","ایندکس‌دی‌بی","ایندکس‌دی‌بی"],
  ["localStorage","n","a small key-value store in the browser","ذخیره محلی مرورگر","لوکال‌استوریج"],
  ["sessionStorage","n","key-value storage that dies with the tab","ذخیره نشست تب","سشن‌استوریج"],
  ["cookie","n","a small piece of data a site stores in the browser","کوکی","کوکی"],
  ["SameSite","n","a cookie attribute that limits cross-site sending","ویژگی سیم‌سایت کوکی","سیم‌سایت"],
  ["CSRF","n","a forged request using a victim's cookies","جعل درخواست بین‌سایتی","سی‌اس‌آراف"],
  ["CSP","n","a policy that limits what a page may load","سیاست امنیت محتوا","سی‌اس‌پی"],
  ["HSTS","n","forcing browsers to use HTTPS","اجبار اچ‌تی‌تی‌پی‌اس","اچ‌اس‌تی‌اس"],
  ["CORS preflight","n","an OPTIONS request that checks a cross-origin call","پیش‌پرواز کورس","پریفلایت"],
  ["content type","n","the MIME type of a payload","نوع محتوا","کانتنت تایپ"],
  ["MIME","n","a label for the format of a file","میم","میم"],
  ["multipart","n","a body made of several parts, used for uploads","بدنه چندقسمتی","مالتی‌پارت"],
  ["FormData","n","a browser object that builds multipart bodies","فرم‌دیتا","فرم‌دیتا"],
  ["Blob","n","an opaque file-like object of bytes","بلاب","بلاب"],
  ["ArrayBuffer","n","a raw binary buffer in JavaScript","آرایه‌بافر","آرایه‌بافر"],
  ["SharedArrayBuffer","n","a buffer that workers can share","بافر اشتراکی","شرد آرایه‌بافر"],
  ["Atomics","n","thread-safe operations on shared buffers","عملیات اتمی روی بافر اشتراکی","اتمیکس"],
  ["WeakMap","n","a map that does not keep keys alive","ویک‌مپ","ویک‌مپ"],
  ["WeakRef","n","a reference that does not prevent collection","ارجاع ضعیف","ویک‌رف"],
  ["FinalizationRegistry","n","callbacks when an object is collected","رجیستری نهایی‌سازی","فاینالیزیشن"],
  ["Proxy object","n","a JS object that intercepts operations","شیء پروکسی جاوااسکریپت","پراکسی آبجکت"],
  ["Reflect","n","a namespace of default object operations","رفلکت","رفلکت"],
  ["Symbol","n","a unique primitive used as a key","سیمبل","سیمبل"],
  ["BigInt","n","an integer of arbitrary size in JavaScript","بیگ‌اینت","بیگ‌اینت"],
  ["temporal","n","a proposed JS API for dates and times","تمپورال","تمپورال"],
  ["Intl","n","the JS namespace for locale-aware formatting","اینتل","اینتل"],
  ["AbortController","n","a way to cancel fetch and other work","کنترل لغو","ابورت"],
  ["ReadableStream","n","a stream of chunks a consumer can pull","جریان خواندنی","ریدبل استریم"],
  ["WritableStream","n","a stream a producer can write into","جریان نوشتنی","رایتابل استریم"],
  ["TransformStream","n","a stream that maps chunks as they pass","جریان تبدیل","ترانسفورم استریم"],
  ["backpressure in streams","n","slowing a producer when a consumer is behind","فشار معکوس در استریم","بک‌پرشر استریم"],
  ["tee","v","to split a stream into two identical ones","دو شاخه کردن استریم","تی کنید"],
  ["enqueue","v","to put an item at the back of a queue","ورود به انتهای صف","انکیو کنید"],
  ["dequeue","v","to take an item from the front of a queue","خروج از ابتدای صف","دیکیو کنید"],
  ["priority queue","n","a queue that pops the best item, not the oldest","صف اولویت","پرایریتی کیو"],
  ["heap sort","n","a sort that uses a binary heap","مرتب‌سازی هیپ","هیپ سورت"],
  ["insertion sort","n","a sort that grows a sorted prefix","مرتب‌سازی درجی","اینسرشن سورت"],
  ["selection sort","n","a sort that repeatedly picks the next minimum","مرتب‌سازی انتخابی","سلکشن سورت"],
  ["merge sort","n","a stable divide-and-conquer sort","مرتب‌سازی ادغامی","مرج سورت"],
  ["counting sort","n","a sort for integers in a small range","مرتب‌سازی شمارشی","کانتینگ سورت"],
  ["radix sort","n","a sort by digits from least to most significant","مرتب‌سازی مبنایی","ردیکس سورت"],
  ["topological sort","n","an order of a DAG that respects edges","مرتب‌سازی توپولوژیک","توپو سورت"],
  ["binary search","n","finding a key in a sorted list by halving","جستجوی دودویی","باینری سرچ"],
  ["two pointers","n","a technique that walks a list from both ends","دو اشاره‌گر","تو پوینترز"],
  ["sliding window","n","a technique that maintains a moving subrange","پنجره لغزان","اسلایدینگ ویندو"],
  ["prefix sum","n","an array of running totals","جمع پیشوندی","پریفیکس سام"],
  ["dynamic programming","n","solving subproblems once and reusing answers","برنامه‌نویسی پویا","دی‌پی"],
  ["greedy","adj","always taking the locally best choice","حریص","گریدی"],
  ["backtracking","n","trying a path and undoing when it fails","پس‌گرد","بک‌ترک"],
  ["divide and conquer","n","splitting a problem, solving parts, combining","تقسیم و حل","دیواید اند کانکر"],
  ["amortized","adj","cheap on average even if some steps are expensive","سرشکن","آمورتیازد"],
  ["space complexity","n","how extra memory grows with input size","پیچیدگی فضا","اسپیس"],
  ["time complexity","n","how runtime grows with input size","پیچیدگی زمان","تایم"],
  ["NP-complete","n","a class of hard decision problems","ان‌پی کامل","ان‌پی"],
  ["heuristic","n","a practical rule that is not always optimal","ابتکار","هیوریستیک"],
  ["approximation algorithm","n","an algorithm with a proven quality bound","الگوریتم تقریبی","اپراکسیمیشن"],
  ["randomized algorithm","n","an algorithm that uses coin flips","الگوریتم تصادفی","رندومایزد"],
  ["hash table","n","an array of buckets addressed by a hash","جدول هش","هش تیبل"],
  ["open addressing","n","storing collisions in the same table","آدرس‌دهی باز","اوپن ادرسینگ"],
  ["chaining","n","storing collisions in a list per bucket","زنجیره‌سازی برخورد","چینیگ"],
  ["consistent hashing","n","a ring that moves few keys when nodes change","هش سازگار","کنسیستنت هش"],
  ["jump consistent hash","n","a simple assignment of keys to numbered buckets","هش پرشی سازگار","جامپ هش"],
  ["cuckoo hashing","n","a scheme that moves items to keep lookups at two slots","هش فاخته","کوکو هش"],
  ["skip list","n","a layered linked list with express lanes","لیست پرشی","اسکیپ لیست"],
  ["trie","n","a tree of prefixes","تری پیشوند","تری"],
  ["suffix array","n","sorted starting positions of all suffixes","آرایه پسوند","سافیکس آرای"],
  ["Fenwick tree","n","a compact structure for prefix sums","درخت فنویک","فنویک"],
  ["segment tree","n","a tree over ranges for fast queries","درخت بازه","سگمنت تری"],
  ["union-find","n","a structure for merging disjoint sets","یونیون-فایند","یونیون فایند"],
  ["minimum spanning tree","n","the cheapest set of edges that connect all nodes","درخت پوشای کمینه","ام‌اس‌تی"],
  ["max flow","n","the largest throughput through a network","بیشینه جریان","مکس فلو"],
  ["bipartite matching","n","pairing two groups with no two sharing an edge","تطابق دوقسمتی","بایپارتایت"],
  ["A-star","n","a shortest-path search with a heuristic","ای‌استار","ای‌استار"],
  ["Bellman-Ford","n","a shortest-path algorithm that allows negative edges","بلمن-فورد","بلمن فورد"],
  ["Floyd-Warshall","n","all-pairs shortest paths","فلوید-وارشال","فلوید"],
  ["KMP","n","a linear-time string matching algorithm","کاته‌موریس-پرات","کی‌ام‌پی"],
  ["Rabin-Karp","n","string matching with rolling hashes","رابین-کارپ","رابین کارپ"],
  ["rolling hash","n","a hash you can update as a window slides","هش غلتان","رولینگ هش"],
  ["bitmask","n","an integer used as a set of flags","بیت‌ماسک","بیت‌ماسک"],
  ["two's complement","n","the usual encoding of signed integers","مکمل دو","توز کامپلیمنت"],
  ["endianness","n","the byte order of a multi-byte integer","ترتیب بایت","اندین"],
  ["little-endian","adj","storing the least significant byte first","اندین کوچک","لیتل اندین"],
  ["big-endian","adj","storing the most significant byte first","اندین بزرگ","بیگ اندین"],
  ["alignment","n","placing values at addresses the CPU likes","تراز حافظه","الاینمنت حافظه"],
  ["padding bytes","n","extra bytes so the next field is aligned","بایت پدینگ تراز","پدینگ بایت"],
  ["ABI","n","the binary calling convention between compiled units","ای‌بی‌آی","ای‌بی‌آی"],
  ["calling convention","n","who saves which registers and how arguments pass","قرارداد فراخوانی","کالینگ کانوشن"],
  ["stack frame","n","the slice of stack one call owns","فریم پشته","استک فریم"],
  ["tail call","n","a call in return position that can reuse the frame","فراخوانی دمی","تیل کال"],
  ["inlining","n","pasting a function body at the call site","درون‌خط کردن تابع","اینلاینینگ"],
  ["dead code elimination","n","removing instructions that cannot run","حذف کد مرده","دی‌سی‌ای"],
  ["constant folding","n","computing constant expressions at compile time","تا کردن ثابت","کانستنت فولد"],
  ["loop unrolling","n","repeating a loop body to cut branch costs","باز کردن حلقه","آنرول"],
  ["vectorization","n","using SIMD on a loop","برداری‌سازی حلقه","وکتری‌زیشن"],
  ["register allocation","n","assigning variables to CPU registers","تخصیص ثبات","رجیستر الوک"],
  ["SSA","n","static single assignment form","فرم انتساب تکی ایستا","اس‌اس‌ای"],
  ["IR","n","an intermediate representation of a program","نمایش میانی","آی‌آر"],
  ["AST","n","an abstract syntax tree","درخت نحو انتزاعی","ای‌اس‌تی"],
  ["CST","n","a concrete syntax tree that keeps every token","درخت نحو عینی","سی‌اس‌تی"],
  ["parse tree","n","the tree a parser builds from a grammar","درخت تجزیه","پارس تری"],
  ["grammar","n","the rules that define a language","دستور زبان","گرمر"],
  ["CFG","n","a context-free grammar; also a control-flow graph","گرامر مستقل از بافت یا گراف کنترل","سی‌اف‌جی"],
  ["control flow","n","the order in which statements run","جریان کنترل","کنترل فلو"],
  ["data flow","n","how values move between statements","جریان داده","دیتا فلو"],
  ["side effect","n","a change besides returning a value","اثر جانبی","ساید افکت"],
  ["pure function","n","a function whose result depends only on its inputs","تابع خالص","پیور فانکشن"],
  ["referential transparency","n","being able to replace a call with its result","شفافیت ارجاعی","رفرنشال"],
  ["higher-order function","n","a function that takes or returns functions","تابع مرتبه بالاتر","هایر اردر"],
  ["currying","n","turning a multi-arg function into a chain of one-arg functions","کاری کردن تابع","کاریینگ"],
  ["partial application","n","filling some arguments now and the rest later","اعمال جزئی","پارشیال اپ"],
  ["point-free","adj","written by composing functions without naming arguments","بدون نام‌گذاری آرگومان","پوینت‌فری"],
  ["algebraic data type","n","a type built from sums and products","نوع جبری داده","ای‌دی‌تی"],
  ["sum type","n","a value that is one of several alternatives","نوع جمع","سام تایپ"],
  ["product type","n","a value that holds several fields at once","نوع ضرب","پرادکت تایپ"],
  ["option type","n","a value that may be present or absent","نوع اختیاری","آپشن"],
  ["result type","n","a value that is success or a typed error","نوع نتیجه","ریزالت تایپ"],
  ["newtype","n","a thin wrapper that the compiler treats as distinct","نوع جدید نازک","نیوتایپ"],
  ["phantom type","n","a type parameter used only at compile time","نوع شبح","فانتوم تایپ"],
  ["type class","n","a set of operations a type can implement","کلاس نوع","تایپ کلس"],
  ["trait","n","a Rust or Scala interface of behavior","تریت","تریت"],
  ["impl","n","an implementation of a trait for a type","پیاده‌سازی تریت","ایمپل"],
  ["lifetime","n","how long a reference is allowed to exist","عمر ارجاع","لایف‌تایم"],
  ["borrow checker","n","the Rust pass that enforces aliasing rules","بررسی‌گر امانت","بارو چکر"],
  ["move semantics","n","transferring ownership instead of copying","معنای انتقال مالکیت","موو"],
  ["copy elision","n","skipping copies the language would otherwise make","حذف کپی","کپی الیژن"],
  ["RAII","n","tying resource lifetime to an object destructor","رایای","رایای"],
  ["smart pointer","n","an object that acts like a pointer with extra rules","اشاره‌گر هوشمند","اسمارت پوینتر"],
  ["unique_ptr","n","a C++ pointer with exclusive ownership","یونیک پوینتر","یونیک پوینتر"],
  ["shared_ptr","n","a C++ pointer with shared ownership","شرد پوینتر","شرد پوینتر"],
  ["Arc","n","an atomically reference-counted pointer in Rust","آرک راست","آرک"],
  ["Rc","n","a single-threaded reference-counted pointer","آرسی راست","آرسی"],
  ["interior mutability","n","mutating through a shared reference via a cell","تغییرپذیری درونی","اینتریور میوت"],
  ["Send","n","a Rust marker for types safe to move to another thread","سند راست","سند"],
  ["Sync","n","a Rust marker for types safe to share across threads","سینک راست","سینک"],
  ["unsafe","n","a block where the compiler trusts the programmer","بلاک ناامن","آن‌سیف"],
  ["undefined behavior","n","operations the language does not define","رفتار تعریف‌نشده","یوبی"],
  ["memory leak","n","memory that is never freed","نشت حافظه","مموری لیک"],
  ["use after free","n","touching memory that was already released","استفاده پس از آزادسازی","یوز افتر فری"],
  ["double free","n","freeing the same allocation twice","آزادسازی دوباره","دابل فری"],
  ["buffer overflow","n","writing past the end of an array","سرریز بافر","بافر اورفلو"],
  ["stack overflow","n","using more stack than the process has","سرریز پشته","استک اورفلو"],
  ["integer overflow","n","a wrap of a too-large integer","سرریز عدد صحیح","اینت اورفلو"],
  ["TOCTOU","n","a race between check and use","رقابت بررسی و استفاده","تاکتو"],
  ["ASLR","n","randomizing where a process is mapped","تصادفی‌سازی فضای نشانی","ای‌اس‌ال‌آر"],
  ["DEP","n","marking data pages non-executable","جلوگیری از اجرای داده","دی‌ای‌پی"],
  ["NX bit","n","a hardware flag that forbids executing a page","بیت ان‌ایکس","ان‌ایکس"],
  ["ROP","n","return-oriented programming, chaining gadgets","برنامه‌نویسی مبتنی بر بازگشت","آر‌او‌پی"],
  ["gadget","n","a short instruction sequence ending in return","گجت","گجت"],
  ["sandboxing","n","running code with reduced privileges","سندباکس کردن","سندباکسینگ"],
  ["seccomp","n","a Linux filter on allowed syscalls","سک‌کمپ","سک‌کمپ"],
  ["cgroup","n","a Linux controller for CPU, memory, and IO","سی‌گروپ","سی‌گروپ"],
  ["namespace isolation","n","Linux isolation of process views of the system","انزوای فضای نام","نیم‌اسپیس"],
  ["capabilities","n","fine-grained privileges on Unix","قابلیت‌های یونیکس","کپابیلیتی"],
  ["rootless","adj","running containers without a root daemon","بدون ریشه","روت‌لس"],
  ["OCI","n","the Open Container Initiative image format","اوسی‌آی","اوسی‌آی"],
  ["containerd","n","a core container runtime","کانتینرد","کانتینرد"],
  ["CRI","n","the Kubernetes container runtime interface","سی‌آر‌آی","سی‌آر‌آی"],
  ["CNI","n","the Kubernetes network plugin interface","سی‌ان‌آی","سی‌ان‌آی"],
  ["CSI","n","the Kubernetes storage plugin interface","سی‌اس‌آی","سی‌اس‌آی"],
  ["pod","n","the smallest Kubernetes deployable unit","پاد","پاد"],
  ["deployment object","n","a Kubernetes object that keeps replica sets","آبجکت دیپلویمنت","دیپلویمنت"],
  ["replica set","n","a controller that keeps N identical pods","مجموعه نسخه","رپلیکا ست"],
  ["StatefulSet","n","pods with stable names and storage","استیت‌فول‌ست","استیت‌فول‌ست"],
  ["DaemonSet","n","one pod per node","دیمِن‌ست","دیمِن‌ست"],
  ["Job object","n","pods that run to completion","جاب کوبرنتیز","جاب آبجکت"],
  ["CronJob","n","a Kubernetes job on a schedule","کرون‌جاب","کرون‌جاب"],
  ["ConfigMap","n","non-secret configuration in Kubernetes","کانفیگ‌مپ","کانفیگ‌مپ"],
  ["Secret object","n","sensitive values stored in the cluster","سکرت کوبرنتیز","سکرت آبجکت"],
  ["Service object","n","a stable network identity for pods","سرویس کوبرنتیز","سرویس آبجکت"],
  ["Ingress","n","HTTP routing into the cluster","اینگرس","اینگرس"],
  ["NetworkPolicy","n","firewall rules for pods","سیاست شبکه","نتورک پالسی"],
  ["HPA","n","a controller that scales pods on metrics","مقیاس‌گذار افقی","اچ‌پی‌ای"],
  ["VPA","n","a controller that resizes pod requests","مقیاس‌گذار عمودی","وی‌پی‌ای"],
  ["cluster autoscaler","n","adding or removing nodes as pods wait","مقیاس‌گذار خوشه","کلاستر اتواسکیلر"],
  ["taint","n","a node mark that repels pods unless they tolerate it","تینت نود","تینت"],
  ["toleration","n","permission for a pod to land on a tainted node","تحمل تینت","تولریشن"],
  ["affinity","n","rules that attract pods to nodes or to each other","تمایل جایگذاری","افینیتی"],
  ["anti-affinity","n","rules that keep pods apart","ضدتمایل","آنتی‌افینیتی"],
  ["probe","n","a health check Kubernetes runs on a pod","پروب سلامت","پروب"],
  ["liveness","n","a probe that restarts an unhealthy container","زنده‌بودن","لایونس"],
  ["readiness","n","a probe that decides if a pod should take traffic","آمادگی","ردینس"],
  ["startup probe","n","a probe that delays the others until boot finishes","پروب راه‌اندازی","استارتاپ پروب"],
];
