/** 1024+ programmer / vibe-coder terms: word, pos, defEn, defFa, faHead */
export const codeCore = [
  ["abstraction","n","hiding details behind a simpler interface","انتزاع؛ پنهان‌کردن جزئیات پشت رابطی ساده‌تر","انتزاع"],
  ["abstract factory","n","a pattern that creates families of related objects","الگوی کارخانهٔ انتزاعی برای ساخت خانواده‌ای از اشیاء مرتبط","کارخانهٔ انتزاعی"],
  ["ACID","n","atomicity, consistency, isolation, durability in databases","چهار ویژگی اتمی بودن، سازگاری، انزوا و دوام در پایگاه داده","ایسید"],
  ["actor model","n","concurrency where isolated actors talk via messages","مدل بازیگر برای همزمانی با پیام بین واحدهای جدا","مدل بازیگر"],
  ["adapter","n","a pattern that translates one interface into another","آداپتور؛ الگویی که یک رابط را به رابط دیگر تبدیل می‌کند","آداپتور"],
  ["agile","n","an iterative way of building software in short cycles","اجایل؛ روش تکرارشونده برای ساخت نرم‌افزار","اجایل"],
  ["algorithm","n","a precise set of steps to solve a problem","الگوریتم؛ مجموعهٔ دقیق گام‌ها برای حل مسئله","الگوریتم"],
  ["alias","n","another name for the same value or command","نام مستعار برای یک مقدار یا فرمان","نام مستعار"],
  ["allocator","n","code that hands out memory","تخصیص‌دهندهٔ حافظه","تخصیص‌دهنده"],
  ["alpha","n","an early, unstable release","نسخهٔ آلفا؛ انتشار اولیه و ناپایدار","آلفا"],
  ["android","n","Google's mobile operating system","اندروید؛ سیستم‌عامل موبایل گوگل","اندروید"],
  ["annotation","n","metadata attached to code","حاشیه؛ فرادادهٔ چسبیده به کد","حاشیه"],
  ["anonymous function","n","a function without a name","تابع بی‌نام","تابع بی‌نام"],
  ["API","n","a contract that lets programs talk to each other","رابط برنامه‌نویسی که ارتباط برنامه‌ها را ممکن می‌کند","ای‌پی‌آی"],
  ["API gateway","n","a single entry that routes requests to services","درگاه ای‌پی‌آی که درخواست‌ها را به سرویس‌ها می‌فرستد","درگاه"],
  ["Apollo","n","a popular GraphQL client and server toolkit","آپولو؛ ابزار گراف‌کیوال","آپولو"],
  ["argument","n","a value passed into a function","آرگومان؛ مقداری که به تابع داده می‌شود","آرگومان"],
  ["array","n","an ordered list of values","آرایه؛ فهرست مرتب مقادیر","آرایه"],
  ["arrow function","n","a compact JavaScript function using =>","تابع پیکانی در جاوااسکریپت","تابع پیکانی"],
  ["artifact","n","a file produced by a build","آرتیفکت؛ فایل خروجی بیلد","آرتیفکت"],
  ["ASGI","n","the async Python interface for web servers","ای‌اس‌جی‌آی؛ رابط ناهمگام پایتون برای سرور وب","ای‌اس‌جی‌آی"],
  ["assembly","n","low-level code close to machine instructions","اسمبلی؛ کد نزدیک به دستور ماشین","اسمبلی"],
  ["assertion","n","a check that must be true during tests","ادعا؛ بررسی که در تست باید درست باشد","ادعا"],
  ["asset","n","a static file such as an image or font","دارایی استاتیک مثل تصویر یا فونت","دارایی"],
  ["assignment","n","storing a value in a variable","انتساب مقدار به متغیر","انتساب"],
  ["async","adj","running without blocking the caller","ناهمگام؛ بدون مسدود کردن فراخوان","ناهمگام"],
  ["asynchronous","adj","not waiting for one task to finish before starting another","غیرهمزمان","غیرهمزمان"],
  ["atomic","adj","completing as one indivisible step","اتمی؛ کامل شدن در یک گام تجزیه‌ناپذیر","اتمی"],
  ["auth","n","short for authentication","احراز هویت","احراز هویت"],
  ["authorization","n","deciding what an identity is allowed to do","مجوزدهی؛ تعیین کارهای مجاز برای هویت","مجوزدهی"],
  ["autocomplete","n","UI that suggests the rest of a word","تکمیل خودکار","تکمیل خودکار"],
  ["automation","n","letting machines do repetitive work","خودکارسازی","خودکارسازی"],
  ["availability","n","the share of time a system is usable","در دسترس بودن سیستم","در دسترس بودن"],
  ["AVL tree","n","a self-balancing binary search tree","درخت ای‌وی‌ال با تعادل خودکار","درخت ای‌وی‌ال"],
  ["AWS","n","Amazon Web Services cloud platform","سرویس ابری آمازون","آمازون"],
  ["axios","n","a popular HTTP client for JavaScript","اکسیوس؛ کلاینت اچ‌تی‌تی‌پی جاوااسکریپت","اکسیوس"],
  ["Azure","n","Microsoft's cloud platform","آژور؛ ابر مایکروسافت","آژور"],
  ["Babel","n","a JavaScript compiler for older browsers","بیبل؛ کامپایلر جاوااسکریپت","بیبل"],
  ["backend","n","the server side of an application","بک‌اند؛ سمت سرور برنامه","بک‌اند"],
  ["backpressure","n","slowing producers when consumers fall behind","فشار معکوس وقتی مصرف‌کننده عقب می‌ماند","فشار معکوس"],
  ["backup","n","a spare copy of data","نسخهٔ پشتیبان","پشتیبان"],
  ["bandwidth","n","how much data a link can carry","پهنای باند","پهنای باند"],
  ["bash","n","a common Unix shell","بش؛ پوستهٔ رایج یونیکس","بش"],
  ["batch","n","a group of jobs processed together","دستهٔ کارها","دسته"],
  ["BDD","n","behavior-driven development","توسعه مبتنی بر رفتار","بی‌دی‌دی"],
  ["benchmark","n","a test that measures speed","بنچمارک؛ آزمون سرعت","بنچمارک"],
  ["BFS","n","breadth-first search on a graph","جستجوی سطح‌اول در گراف","بی‌اف‌اس"],
  ["big O","n","notation for how cost grows with input size","نماد اُ بزرگ برای رشد هزینه","اُ بزرگ"],
  ["binary","n","base-two numbers; compiled machine code","باینری؛ مبنای دو یا کد ماشین","باینری"],
  ["bind","v","to attach a handler or a network port","اتصال هندلر یا پورت شبکه","اتصال دهید"],
  ["bit","n","a binary digit, zero or one","بیت؛ رقم باینری","بیت"],
  ["bitmap","n","an image stored as a grid of pixels","بیت‌مپ؛ تصویر شبکه‌ای از پیکسل","بیت‌مپ"],
  ["bitwise","adj","operating on individual bits","عمل بیتی","بیتی"],
  ["block","n","a group of statements; a chunk of data","بلوک دستورات یا داده","بلوک"],
  ["blockchain","n","a chained ledger of signed blocks","بلاکچین؛ دفتر کل زنجیره‌ای","بلاکچین"],
  ["bloom filter","n","a compact structure that may say an item is present","فیلتر بلوم برای عضویت احتمالی","فیلتر بلوم"],
  ["blue-green","n","a deploy style that switches between two live environments","استقرار آبی‌سبز با دو محیط زنده","آبی‌سبز"],
  ["boolean","n","a true or false value","مقدار بولی درست یا نادرست","بولی"],
  ["bootstrap","v","to start a system from a small core","راه‌اندازی اولیه سیستم","راه‌اندازی کنید"],
  ["bottleneck","n","the slowest step that limits the whole system","گلوگاه","گلوگاه"],
  ["bound","n","a limit on a value or index","کران","کران"],
  ["branch","n","a line of commits in git","شاخه در گیت","شاخه"],
  ["breakpoint","n","a pause point in a debugger","نقطه توقف در دیباگر","نقطه توقف"],
  ["broadcast","v","to send one message to many listeners","پخش پیام برای شنوندگان زیاد","پخش کنید"],
  ["browser","n","a program that displays web pages","مرورگر وب","مرورگر"],
  ["B-tree","n","a balanced tree used in databases","بی‌تری؛ درخت متوازن پایگاه داده","بی‌تری"],
  ["bubble sort","n","a simple sort that swaps neighbors","مرتب‌سازی حبابی","مرتب‌سازی حبابی"],
  ["buffer","n","temporary storage for data in motion","بافر؛ ذخیره موقت داده","بافر"],
  ["bug","n","a defect in software","باگ؛ نقص نرم‌افزار","باگ"],
  ["build","n","the process of turning source into artifacts","بیلد؛ تبدیل سورس به خروجی","بیلد"],
  ["bundler","n","a tool that packs modules for the browser","باندلر؛ ابزار بسته‌بندی ماژول","باندلر"],
  ["bytecode","n","portable instructions for a virtual machine","بایت‌کد برای ماشین مجازی","بایت‌کد"],
  ["cache","n","fast storage of recently used data","کش؛ ذخیره سریع دادهٔ پرتکرار","کش"],
  ["callback","n","a function passed to be called later","کال‌بک؛ تابعی که بعداً صدا زده می‌شود","کال‌بک"],
  ["camelCase","n","a naming style like thisWordHere","نام‌گذاری شتری مثل thisWord","شتری"],
  ["canary","n","a small rollout to a slice of users","انتشار قناری برای بخشی از کاربران","قناری"],
  ["canvas","n","an HTML element for drawing pixels","بوم اچ‌تی‌ام‌ال برای رسم","بوم"],
  ["CAP theorem","n","a trade-off among consistency, availability, partition tolerance","قضیه کپ درباره سازگاری، دسترس‌پذیری و تحمل افراز","قضیه کپ"],
  ["CDN","n","a network that serves files from nearby edges","سی‌دی‌ان؛ شبکهٔ توزیع محتوا","سی‌دی‌ان"],
  ["CI","n","continuous integration of every change","یکپارچه‌سازی پیوسته","سی‌آی"],
  ["cipher","n","an algorithm that encrypts data","رمز","رمز"],
  ["circuit breaker","n","a guard that stops calling a failing service","مدارشکن که فراخوانی سرویس خراب را قطع می‌کند","مدارشکن"],
  ["class","n","a blueprint for objects","کلاس؛ طرح اشیاء","کلاس"],
  ["CLI","n","a command-line interface","رابط خط فرمان","خط فرمان"],
  ["client","n","software that requests a service","کلاینت؛ نرم‌افزار درخواست‌کننده","کلاینت"],
  ["clone","v","to copy a git repository","کلون کردن مخزن گیت","کلون کنید"],
  ["closure","n","a function that remembers variables from its outer scope","کلژر؛ تابعی که محیط بیرونی را به یاد می‌آورد","کلژر"],
  ["cloud","n","computers you rent over the internet","ابر","ابر"],
  ["cluster","n","a group of machines working as one","خوشهٔ ماشین‌ها","خوشه"],
  ["CMS","n","a content management system","سیستم مدیریت محتوا","سی‌ام‌اس"],
  ["code review","n","reading a teammate's change before it lands","بازبینی کد","بازبینی کد"],
  ["codegen","n","generating source from a schema or template","تولید کد از طرح یا قالب","تولید کد"],
  ["cohesion","n","how closely related the parts of a module are","انسجام درون ماژول","انسجام"],
  ["collision","n","two keys mapping to the same slot","برخورد هش","برخورد"],
  ["commit","n","a saved snapshot in git","کامیت؛ تصویر ذخیره‌شده در گیت","کامیت"],
  ["compiler","n","a program that translates source to machine code","کامپایلر","کامپایلر"],
  ["complexity","n","how resource use grows with input size","پیچیدگی محاسباتی","پیچیدگی"],
  ["component","n","a reusable piece of UI or logic","کامپوننت؛ قطعهٔ قابل استفاده مجدد","کامپوننت"],
  ["compose","v","to build larger functions from smaller ones","ترکیب توابع کوچک‌تر","ترکیب کنید"],
  ["composition","n","combining objects instead of inheriting","ترکیب به‌جای وراثت","ترکیب"],
  ["compression","n","making data smaller to store or send","فشرده‌سازی","فشرده‌سازی"],
  ["concurrency","n","several tasks in progress at overlapping times","همزمانی کارها","همزمانی"],
  ["config","n","settings that change how a program runs","پیکربندی","پیکربندی"],
  ["const","n","a binding that cannot be reassigned","ثابت","ثابت"],
  ["constructor","n","a function that creates an instance","سازندهٔ شیء","سازنده"],
  ["container","n","an isolated process with its own files","کانتینر","کانتینر"],
  ["context","n","data available to a call without extra arguments","بافت اجرایی","بافت"],
  ["continuous delivery","n","shipping every good build to production-ready","تحویل پیوسته","تحویل پیوسته"],
  ["controller","n","code that handles a request and picks a response","کنترلر","کنترلر"],
  ["coroutine","n","a function that can pause and resume","هم‌روال","هم‌روال"],
  ["CORS","n","browser rules for cross-origin HTTP","کورس؛ قوانین مرورگر برای مبدأ متقاطع","کورس"],
  ["CPU","n","the chip that executes instructions","پردازنده","پردازنده"],
  ["crash","n","an unexpected process death","کرش؛ توقف ناگهانی فرایند","کرش"],
  ["CRC","n","a checksum that detects accidental changes","سی‌آرسی؛ جمع‌آزمایی تغییرات تصادفی","سی‌آرسی"],
  ["cron","n","a scheduler for time-based jobs","کرون؛ زمان‌بند کارها","کرون"],
  ["cross-platform","adj","running on more than one operating system","چندسکویی","چندسکویی"],
  ["CRUD","n","create, read, update, delete","کراد؛ ساخت، خواندن، به‌روزرسانی، حذف","کراد"],
  ["crypto","n","cryptography used to protect data","رمزنگاری","رمزنگاری"],
  ["CSS","n","the language that styles web pages","سی‌اس‌اس؛ زبان استایل وب","سی‌اس‌اس"],
  ["CSV","n","comma-separated values in a text file","سی‌اس‌وی؛ مقادیر جداشده با ویرگول","سی‌اس‌وی"],
  ["cursor","n","the insertion point; a database iterator","مکان‌نما؛ پیمایشگر پایگاه داده","مکان‌نما"],
  ["CVE","n","a public identifier for a known vulnerability","شناسه آسیب‌پذیری سی‌وی‌ای","سی‌وی‌ای"],
  ["DAG","n","a directed acyclic graph","گراف جهت‌دار بدون دور","دگ"],
  ["daemon","n","a background process","دیمِن؛ فرایند پس‌زمینه","دیمِن"],
  ["dark mode","n","a UI theme with a dark background","حالت تاریک","حالت تاریک"],
  ["dashboard","n","a screen of key metrics","داشبورد شاخص‌ها","داشبورد"],
  ["database","n","an organized store of records","پایگاه داده","پایگاه داده"],
  ["datagram","n","a self-contained network packet","دیتاگرام؛ بسته مستقل شبکه","دیتاگرام"],
  ["deadlock","n","two tasks each waiting for the other","بن‌بست","بن‌بست"],
  ["debounce","v","to wait until input pauses before running","دبانس کردن تا توقف ورودی","دبانس کنید"],
  ["debug","v","to find and fix defects","دیباگ کردن","دیباگ کنید"],
  ["declaration","n","introducing a name and its type","اعلان نام و نوع","اعلان"],
  ["decorator","n","a wrapper that adds behavior","دکوراتور؛ پوششی که رفتار می‌افزاید","دکوراتور"],
  ["decouple","v","to reduce how tightly two parts depend","کاهش وابستگی قطعات","جدا کنید"],
  ["deep copy","n","a clone that duplicates nested values","کپی عمیق","کپی عمیق"],
  ["default","n","the value used when none is given","مقدار پیش‌فرض","پیش‌فرض"],
  ["defer","v","to postpone work until later in the turn","به تعویق انداختن کار","به تعویق بیندازید"],
  ["dependency","n","another package your code needs","وابستگی بسته‌ای","وابستگی"],
  ["deploy","v","to put a build into a live environment","مستقر کردن","مستقر کنید"],
  ["deprecated","adj","still working but marked for removal","منسوخ‌شده","منسوخ"],
  ["deserialization","n","turning bytes back into objects","بازسازی شیء از بایت","بازسازی"],
  ["design pattern","n","a reusable solution to a common design problem","الگوی طراحی","الگوی طراحی"],
  ["destructure","v","to unpack fields from an object or array","باز کردن فیلدها از شیء یا آرایه","باز کنید"],
  ["dev server","n","a local server used while coding","سرور توسعه محلی","سرور توسعه"],
  ["devtools","n","browser tools for inspecting pages and scripts","ابزارهای توسعه‌دهنده مرورگر","ابزار توسعه"],
  ["DFS","n","depth-first search","جستجوی عمق‌اول","دی‌اف‌اس"],
  ["DHCP","n","a protocol that assigns IP addresses","دی‌اچ‌سی‌پی؛ تخصیص نشانی آی‌پی","دی‌اچ‌سی‌پی"],
  ["dictionary","n","a map from keys to values","دیکشنری؛ نگاشت کلید به مقدار","دیکشنری"],
  ["diff","n","a display of what changed","دیف؛ نمایش تغییرات","دیف"],
  ["Dijkstra","n","an algorithm for shortest paths","الگوریتم دایکسترا برای کوتاه‌ترین مسیر","دایکسترا"],
  ["directory","n","a folder that holds files","پوشه","پوشه"],
  ["dispatch","v","to send an action to a store or worker","ارسال اکشن","ارسال کنید"],
  ["distributed","adj","running across many machines","توزیع‌شده روی چند ماشین","توزیع‌شده"],
  ["Django","n","a Python web framework","جنگو؛ فریم‌ورک وب پایتون","جنگو"],
  ["DLL","n","a Windows shared library","دی‌ال‌ال؛ کتابخانه اشتراکی ویندوز","دی‌ال‌ال"],
  ["DNS","n","the system that maps names to IP addresses","دی‌ان‌اس؛ تبدیل نام به آی‌پی","دی‌ان‌اس"],
  ["Docker","n","a tool for building and running containers","داکر","داکر"],
  ["DOM","n","the tree of elements in a web page","دام؛ درخت عناصر صفحه","دام"],
  ["domain","n","a business area; a network name","دامنه کسب‌وکار یا نام شبکه","دامنه"],
  ["DRY","n","don't repeat yourself","اصل تکرارنکردن","درای"],
  ["DSL","n","a language made for one problem space","زبان دامنه خاص","دی‌اس‌ال"],
  ["DTO","n","a data transfer object","شیء انتقال داده","دی‌تی‌او"],
  ["duck typing","n","judging type by behavior, not name","نوع‌دهی اردکی بر اساس رفتار","نوع‌دهی اردکی"],
  ["dump","n","a snapshot of memory or a database","دامپ حافظه یا پایگاه داده","دامپ"],
  ["dynamic typing","n","checking types while the program runs","نوع‌دهی پویا در زمان اجرا","نوع‌دهی پویا"],
  ["EC2","n","Amazon's virtual machine service","ای‌سی۲؛ ماشین مجازی آمازون","ای‌سی۲"],
  ["edge","n","servers close to users","لبه شبکه نزدیک کاربر","لبه"],
  ["Electron","n","a toolkit for desktop apps with web tech","الکترون برای اپ دسکتاپ با وب","الکترون"],
  ["Elixir","n","a functional language on the Erlang VM","الیکسیر","الیکسیر"],
  ["Elm","n","a functional language for reliable web UIs","الم برای رابط وب قابل اعتماد","الم"],
  ["embed","v","to place one document or widget inside another","جاسازی کردن","جاسازی کنید"],
  ["emitter","n","an object that fires named events","صادرکننده رویداد","صادرکننده"],
  ["encapsulation","n","keeping internals private behind a public API","کپسوله‌سازی","کپسوله‌سازی"],
  ["encryption","n","scrambling data so only keys can read it","رمزنگاری داده","رمزنگاری"],
  ["endpoint","n","a URL that a service answers","نقطه پایانی سرویس","نقطه پایانی"],
  ["engine","n","the core that executes a language or game","موتور اجرا","موتور"],
  ["enum","n","a type with a fixed set of named values","نوع شمارشی","شمارشی"],
  ["env","n","environment variables","متغیرهای محیطی","محیط"],
  ["epoll","n","a Linux API for watching many sockets","ای‌پول لینوکس برای سوکت‌های زیاد","ای‌پول"],
  ["Erlang","n","a language built for concurrent telecom systems","ارلنگ","ارلنگ"],
  ["error","n","a failed operation","خطا","خطا"],
  ["escape","v","to mark special characters so they are literal","گریز دادن نویسه‌های خاص","گریز دهید"],
  ["ESLint","n","a linter for JavaScript and TypeScript","ای‌اس‌لینت","ای‌اس‌لینت"],
  ["event","n","something that happened that code can react to","رویداد","رویداد"],
  ["event loop","n","the cycle that runs queued callbacks","حلقه رویداد","حلقه رویداد"],
  ["exception","n","an error thrown up the call stack","استثنا","استثنا"],
  ["executor","n","a pool that runs submitted tasks","اجراکننده وظایف","اجراکننده"],
  ["expression","n","code that evaluates to a value","عبارت","عبارت"],
  ["extension","n","a plugin that adds features","افزونه","افزونه"],
  ["FaaS","n","functions as a service","تابع به‌عنوان سرویس","فاس"],
  ["failover","n","switching to a backup when the primary dies","جابه‌جایی به پشتیبان هنگام خرابی","جابه‌جایی خرابی"],
  ["false positive","n","an alert that was not a real problem","هشدار نادرست","هشدار نادرست"],
  ["feature flag","n","a switch that turns a feature on without a new deploy","پرچم ویژگی","پرچم ویژگی"],
  ["fetch","v","to request a resource over HTTP","واکشی منبع از اچ‌تی‌تی‌پی","واکشی کنید"],
  ["FIFO","n","first in, first out","اول وارد، اول خارج","فیفو"],
  ["file","n","a named blob of bytes on disk","فایل","فایل"],
  ["filter","v","to keep only items that match a test","فیلتر کردن","فیلتر کنید"],
  ["Firebase","n","Google's backend-as-a-service platform","فایربیس","فایربیس"],
  ["firewall","n","a filter for network traffic","فایروال","فایروال"],
  ["firmware","n","software stored on a device's chip","ثابت‌افزار","ثابت‌افزار"],
  ["fixture","n","known data used by tests","دادهٔ ثابت تست","فیکسچر"],
  ["flag","n","a boolean option","پرچم بولی","پرچم"],
  ["flake","n","a test that fails only sometimes","تست شکننده","تست شکننده"],
  ["flatten","v","to turn nested lists into one list","تخت کردن لیست تو در تو","تخت کنید"],
  ["float","n","a number with a fractional part","عدد اعشاری","اعشاری"],
  ["fluent","adj","an API designed to chain calls","رابط روان با زنجیرهٔ فراخوانی","روان"],
  ["Flutter","n","Google's UI toolkit for mobile and desktop","فلاتر","فلاتر"],
  ["Flux","n","a one-way data flow pattern for UI","فلاکس؛ جریان یک‌سویه داده","فلاکس"],
  ["fork","v","to copy a repository to your account","فورک کردن مخزن","فورک کنید"],
  ["format","v","to arrange data into a standard layout","قالب‌بندی کردن","قالب‌بندی کنید"],
  ["Fortran","n","an early language for numeric computing","فورترن","فورترن"],
  ["forward","v","to send a request on to another handler","ارسال درخواست به هندلر دیگر","ارسال کنید"],
  ["FPS","n","frames per second","فریم بر ثانیه","فریم بر ثانیه"],
  ["fragment","n","a piece of UI or a URL hash","قطعه رابط یا هش نشانی","قطعه"],
  ["frame","n","one still image in an animation; a call-stack entry","فریم انیمیشن یا پشته فراخوانی","فریم"],
  ["framework","n","a structure that your app fills in","فریم‌ورک","فریم‌ورک"],
  ["frontend","n","the user-facing part of an app","فرانت‌اند","فرانت‌اند"],
  ["FSM","n","a finite-state machine","ماشین حالت محدود","ماشین حالت"],
  ["full-stack","adj","working on both client and server","فول‌استک","فول‌استک"],
  ["function","n","a named block that takes input and returns output","تابع","تابع"],
  ["functor","n","a type you can map a function over","فانکتور","فانکتور"],
  ["fuzzing","n","testing with random unexpected input","فازینگ با ورودی تصادفی","فازینگ"],
  ["garbage collection","n","automatic reclaim of unused memory","جمع‌آوری زباله حافظه","جمع‌آوری زباله"],
  ["gateway","n","a node that routes traffic between networks","دروازه شبکه","دروازه"],
  ["GCC","n","the GNU compiler collection","جی‌سی‌سی","جی‌سی‌سی"],
  ["generator","n","a function that yields a sequence of values","مولد دنباله مقادیر","مولد"],
  ["generics","n","code parameterized by types","ژنریک؛ کد پارامتری با نوع","ژنریک"],
  ["git","n","a distributed version-control system","گیت","گیت"],
  ["GitHub","n","a host for git repositories","گیت‌هاب","گیت‌هاب"],
  ["GitLab","n","a git host with built-in CI","گیت‌لب","گیت‌لب"],
  ["gitignore","n","a file listing paths git should skip","فایل نادیده‌گرفتن گیت","گیت‌آیگنور"],
  ["global","adj","visible everywhere in a program","سراسری","سراسری"],
  ["Go","n","Google's compiled language for servers","زبان گو","گو"],
  ["Gradle","n","a build tool used in JVM and Android projects","گرادل","گرادل"],
  ["GraphQL","n","a query language for APIs","گراف‌کیوال","گراف‌کیوال"],
  ["grep","n","a tool that searches text by pattern","گرپ؛ جستجوی متن با الگو","گرپ"],
  ["grid","n","a layout of rows and columns","شبکه ردیف و ستون","شبکه"],
  ["GUI","n","a graphical user interface","رابط گرافیکی کاربر","جی‌یوآی"],
  ["gzip","n","a common compression format","جی‌زیپ","جی‌زیپ"],
  ["hackathon","n","a short intense building event","هکاتون","هکاتون"],
  ["Hadoop","n","a system for large distributed data","هادوپ","هادوپ"],
  ["handler","n","a function that reacts to an event or request","هندلر","هندلر"],
  ["handshake","n","the first messages that set up a connection","دست‌دادن اولیه اتصال","دست‌دادن"],
  ["hash","n","a fixed-size fingerprint of data","هش","هش"],
  ["Haskell","n","a purely functional language","هسکل","هسکل"],
  ["headless","adj","running without a visible window","بدون رابط گرافیکی","هدلس"],
  ["heap","n","memory for dynamically allocated objects","هیپ حافظه پویا","هیپ"],
  ["hello world","n","the smallest program that prints a greeting","برنامه سلام دنیا","سلام دنیا"],
  ["hex","n","base-sixteen notation","مبنای شانزده","هگز"],
  ["HMR","n","hot module replacement during development","جایگزینی داغ ماژول","اچ‌ام‌آر"],
  ["HOC","n","a higher-order component in React","کامپوننت مرتبه بالاتر","اچ‌او‌سی"],
  ["hook","n","a function that taps into a framework lifecycle","هوک","هوک"],
  ["host","n","a machine that runs software","میزبان","میزبان"],
  ["hotfix","n","an urgent patch in production","رفع فوری در تولید","رفع فوری"],
  ["HTML","n","the markup language of web pages","اچ‌تی‌ام‌ال","اچ‌تی‌ام‌ال"],
  ["HTTP","n","the protocol of the web","اچ‌تی‌تی‌پی","اچ‌تی‌تی‌پی"],
  ["HTTPS","n","HTTP over TLS","اچ‌تی‌تی‌پی‌اس","اچ‌تی‌تی‌پی‌اس"],
  ["hydration","n","attaching event handlers to server-rendered HTML","هیدریشن رابط پس از اچ‌تی‌ام‌ال سرور","هیدریشن"],
  ["hypervisor","n","software that runs virtual machines","هایپروانیزور","هایپروانیزور"],
  ["I/O","n","input and output","ورودی و خروجی","آی‌او"],
  ["IaaS","n","infrastructure as a service","زیرساخت به‌عنوان سرویس","آی‌آس"],
  ["idempotent","adj","safe to retry because repeating does not change the result","ایدمپوتنت؛ تکرار بی‌اثر بر نتیجه","ایدمپوتنت"],
  ["identifier","n","a name in source code","شناسه","شناسه"],
  ["idle","adj","not currently doing work","بیکار","بیکار"],
  ["iframe","n","an HTML frame that embeds another page","آی‌فریم","آی‌فریم"],
  ["immutability","n","never changing a value after it is created","تغییرناپذیری","تغییرناپذیری"],
  ["import","v","to load a module","وارد کردن ماژول","وارد کنید"],
  ["index","n","a structure that speeds up lookups","ایندکس","ایندکس"],
  ["inference","n","the compiler guessing a type; a model producing output","استنتاج نوع یا خروجی مدل","استنتاج"],
  ["infra","n","servers, networks, and related machinery","زیرساخت","زیرساخت"],
  ["inheritance","n","a type receiving fields from a parent type","وراثت","وراثت"],
  ["init","v","to set something up for the first time","مقداردهی اولیه","مقداردهی کنید"],
  ["injection","n","slipping untrusted data into a query or command","تزریق داده نامعتبر","تزریق"],
  ["inline","adj","placed directly in the surrounding code","درون‌خطی","درون‌خطی"],
  ["inode","n","a Unix structure that describes a file","آی‌نود یونیکس","آی‌نود"],
  ["input","n","data coming into a program","ورودی","ورودی"],
  ["instance","n","one object created from a class","نمونه شیء","نمونه"],
  ["int","n","an integer type","عدد صحیح","اینت"],
  ["integration","n","connecting parts so they work together","یکپارچه‌سازی","یکپارچه‌سازی"],
  ["interface","n","a named set of operations a type must support","رابط","رابط"],
  ["interpreter","n","a program that executes source directly","مفسر","مفسر"],
  ["invariant","n","a condition that must always hold","ناوردا","ناوردا"],
  ["IoC","n","inversion of control","وارونگی کنترل","آی‌او‌سی"],
  ["IoT","n","internet of things","اینترنت اشیاء","آی‌او‌تی"],
  ["IPC","n","inter-process communication","ارتباط بین‌فرایندی","آی‌پی‌سی"],
  ["IP","n","internet protocol; an address on a network","آی‌پی","آی‌پی"],
  ["isolation","n","keeping work from interfering","انزوای کارها","انزوا"],
  ["iterator","n","an object that walks a sequence","پیمایشگر","پیمایشگر"],
  ["JAMstack","n","JavaScript, APIs, and markup as an architecture","جم‌استک","جم‌استک"],
  ["Java","n","a class-based language on the JVM","جاوا","جاوا"],
  ["JavaScript","n","the language of the web browser","جاوااسکریپت","جاوااسکریپت"],
  ["JDK","n","the Java development kit","جی‌دی‌کی","جی‌دی‌کی"],
  ["Jest","n","a JavaScript test runner","جست","جست"],
  ["JIT","n","just-in-time compilation","کامپایل در لحظه اجرا","جیت"],
  ["job","n","a unit of work in a queue","کار در صف","جاب"],
  ["join","v","to combine rows from two tables","پیوند ردیف جداول","پیوند دهید"],
  ["jq","n","a tool for slicing JSON on the command line","جی‌کیو برای جیسون","جی‌کیو"],
  ["jQuery","n","a classic library for DOM work","جی‌کوئری","جی‌کوئری"],
  ["JSON","n","JavaScript object notation","جیسون","جیسون"],
  ["JSX","n","an HTML-like syntax for JavaScript UI","جی‌اس‌ایکس","جی‌اس‌ایکس"],
  ["JVM","n","the Java virtual machine","ماشین مجازی جاوا","جی‌وی‌ام"],
  ["JWT","n","a signed JSON web token","توکن وب جیسون","جی‌دبلیوتی"],
  ["K8s","n","short for Kubernetes","کی۸اس؛ کوتاه‌شده کوبرنتیز","کی۸اس"],
  ["Kafka","n","a distributed log for event streams","کافکا","کافکا"],
  ["kebab-case","n","a naming style like this-word-here","نام‌گذاری کبابی با خط تیره","کبابی"],
  ["kernel","n","the core of an operating system","هسته سیستم‌عامل","هسته"],
  ["key","n","an identifier used to look up a value","کلید","کلید"],
  ["keypair","n","a public key plus a private key","جفت کلید","جفت کلید"],
  ["keyword","n","a reserved word in a language","کلمه کلیدی","کلمه کلیدی"],
  ["KISS","n","keep it simple, stupid","اصل ساده‌نگه‌داشتن","کیس"],
  ["Kotlin","n","a modern language on the JVM and for Android","کاتلین","کاتلین"],
  ["Kubernetes","n","a system that schedules containers","کوبرنتیز","کوبرنتیز"],
  ["KV store","n","a database of keys and values","ذخیره کلید-مقدار","کلید-مقدار"],
  ["lambda","n","an anonymous function; a serverless function","لامبدا","لامبدا"],
  ["latency","n","the wait before a response starts","تأخیر پاسخ","تأخیر"],
  ["lazy","adj","computed only when first needed","تنبل؛ محاسبه در زمان نیاز","تنبل"],
  ["leetcode","n","a site of coding interview puzzles","لیت‌کد","لیت‌کد"],
  ["legacy","adj","old code still in production","کد قدیمی در تولید","لگسی"],
  ["let","n","a block-scoped binding in JavaScript","لت؛ اتصال محدود به بلوک","لت"],
  ["lexer","n","the stage that splits source into tokens","تحلیل‌گر واژگانی","لکسر"],
  ["library","n","reusable code you import","کتابخانه","کتابخانه"],
  ["lifecycle","n","the stages an object or page goes through","چرخه حیات","چرخه حیات"],
  ["LIFO","n","last in, first out","آخر وارد، اول خارج","لیفو"],
  ["linter","n","a tool that flags likely mistakes","لینتر","لینتر"],
  ["Linux","n","a family of Unix-like operating systems","لینوکس","لینوکس"],
  ["Lisp","n","a family of languages built on lists","لیسپ","لیسپ"],
  ["list","n","an ordered collection","فهرست","فهرست"],
  ["literal","n","a value written directly in source","مقدار تحت‌اللفظی","لیترال"],
  ["load balancer","n","a node that spreads traffic across servers","توزیع‌کننده بار","توزیع بار"],
  ["localhost","n","the computer you are sitting at","لوکال‌هاست","لوکال‌هاست"],
  ["lock","n","a mutex that only one task may hold","قفل انحصاری","قفل"],
  ["log","n","a running record of events","لاگ رویدادها","لاگ"],
  ["logger","n","a helper that writes log lines","لاگر","لاگر"],
  ["loop","n","a construct that repeats work","حلقه تکرار","حلقه"],
  ["LRU","n","least-recently-used eviction","حذف کم‌استفاده‌ترین","ال‌آر‌یو"],
  ["LSP","n","the language server protocol","پروتکل سرور زبان","ال‌اس‌پی"],
  ["Lua","n","a small embeddable language","لوآ","لوآ"],
  ["macro","n","code that writes other code at compile time","ماکرو","ماکرو"],
  ["main","n","the entry function of a program","تابع اصلی برنامه","مین"],
  ["Makefile","n","a file of build recipes","فایل میک","میک‌فایل"],
  ["malloc","n","a C function that allocates heap memory","مالوک؛ تخصیص هیپ در سی","مالوک"],
  ["map","n","a collection of keys to values; a transform over a list","نگاشت","نگاشت"],
  ["markdown","n","a lightweight markup language for text","مارک‌داون","مارک‌داون"],
  ["marshal","v","to pack a value for the wire","بسته‌بندی مقدار برای شبکه","بسته‌بندی کنید"],
  ["match","v","to choose a branch by pattern","تطبیق الگو","تطبیق دهید"],
  ["memoize","v","to cache the result of a function","ذخیره نتیجه تابع","ذخیره کنید"],
  ["memory","n","the RAM a process uses","حافظه","حافظه"],
  ["merge","v","to combine two branches","ادغام شاخه‌ها","ادغام کنید"],
  ["message queue","n","a buffer of jobs between services","صف پیام","صف پیام"],
  ["metadata","n","data about data","فراداده","فراداده"],
  ["method","n","a function attached to an object","متد","متد"],
  ["metrics","n","numeric measurements of a system","معیارهای عددی سیستم","معیار"],
  ["microfrontend","n","a UI composed of independently shipped pieces","میکروفرانت‌اند","میکروفرانت‌اند"],
  ["microservice","n","a small independently deployable service","میکروسرویس","میکروسرویس"],
  ["middleware","n","a function that sits in a request pipeline","میان‌افزار","میان‌افزار"],
  ["minify","v","to shrink source by stripping space","کوچک‌سازی سورس","کوچک کنید"],
  ["minimax","n","an algorithm that picks the least-bad move","مینی‌مکس","مینی‌مکس"],
  ["mock","n","a fake stand-in used in tests","ماک تست","ماک"],
  ["module","n","a file that exports names","ماژول","ماژول"],
  ["monad","n","a pattern for sequencing effectful computations","موناد","موناد"],
  ["MongoDB","n","a document database","مونگو","مونگو"],
  ["monorepo","n","many projects in one repository","مونوریپو","مونوریپو"],
  ["mutex","n","mutual exclusion lock","قفل انحصار متقابل","میوتکس"],
  ["MVC","n","model-view-controller","مدل-نما-کنترلر","ام‌وی‌سی"],
  ["MVVM","n","model-view-viewmodel","مدل-نما-ویومدل","ام‌وی‌وی‌ام"],
  ["namespace","n","a prefix that keeps names from clashing","فضای نام","فضای نام"],
  ["NaN","n","not a number","نان؛ غیرعدد","نان"],
  ["native","adj","built for a specific operating system","بومی سیستم‌عامل","بومی"],
  ["navigation","n","moving between screens","ناوبری","ناوبری"],
  ["NestJS","n","a TypeScript framework for servers","نست‌جی‌اس","نست"],
  ["network","n","linked machines that exchange packets","شبکه","شبکه"],
  ["Next.js","n","a React framework with routing and rendering","نکست‌جی‌اس","نکست"],
  ["nginx","n","a popular reverse proxy and web server","انجین‌ایکس","انجین‌ایکس"],
  ["nil","n","an empty value in some languages","نیل؛ مقدار خالی","نیل"],
  ["N+1","n","a query pattern that hits the database once per row","مشکل ان‌پلاس‌یک در کوئری","ان‌پلاس‌یک"],
  ["node","n","an item in a tree; a JavaScript runtime","گره؛ یا ران‌تایم نود","نود"],
  ["Node.js","n","JavaScript on the server","نود‌جی‌اس","نود‌جی‌اس"],
  ["normalization","n","structuring tables to reduce duplication","نرمال‌سازی جداول","نرمال‌سازی"],
  ["NoSQL","n","databases that are not relational SQL","نو‌اس‌کیوال","نو‌اس‌کیوال"],
  ["npm","n","the Node package manager","ان‌پی‌ام","ان‌پی‌ام"],
  ["null","n","a value meaning nothing is there","نال","نال"],
  ["nullish","adj","null or undefined","نالیش؛ نال یا تعریف‌نشده","نالیش"],
  ["OAuth","n","a standard for delegated login","اواوت","اواوت"],
  ["object","n","a value with named fields","شیء","شیء"],
  ["observable","n","a stream you can subscribe to","آبزروبل","آبزروبل"],
  ["observer","n","a pattern that notifies listeners of changes","ناظر تغییرات","ناظر"],
  ["OCR","n","optical character recognition","بازشناسی نویسه نوری","او‌سی‌آر"],
  ["off-by-one","n","an error that misses a boundary by a single step","خطای یکی‌کم‌یا‌زیاد","یکی‌کم"],
  ["OIDC","n","OpenID Connect, an identity layer on OAuth","اوآی‌دی‌سی","اوآی‌دی‌سی"],
  ["ORM","n","a mapper between objects and tables","اورم","اورم"],
  ["OS","n","operating system","سیستم‌عامل","سیستم‌عامل"],
  ["overflow","n","a value too large for its type; extra content","سرریز","سرریز"],
  ["overlay","n","UI drawn on top of other UI","رویه روی رابط","رویه"],
  ["package","n","a named bundle of modules","بسته","بسته"],
  ["padding","n","space inside a box; extra bytes in a protocol","حاشیه داخلی؛ پدینگ","پدینگ"],
  ["page","n","one screen of a web app","صفحه","صفحه"],
  ["pair programming","n","two people writing at one keyboard","برنامه‌نویسی دونفره","برنامه‌نویسی دونفره"],
  ["palette","n","the set of colors in a design","پالت رنگ","پالت"],
  ["parallel","adj","running at the same instant","موازی","موازی"],
  ["param","n","a named input to a function","پارامتر","پارامتر"],
  ["parse","v","to turn text into a structured value","تجزیه متن","تجزیه کنید"],
  ["parser","n","the code that parses","پارسر","پارسر"],
  ["partial","n","a function with some arguments already filled","تابع جزئی","تابع جزئی"],
  ["partition","n","a slice of data or a network split","افراز داده یا شبکه","افراز"],
  ["pass-by-reference","n","giving a function access to the original value","عبور با ارجاع","عبور با ارجاع"],
  ["password","n","a secret used to prove identity","گذرواژه","گذرواژه"],
  ["patch","n","a small change set","پچ؛ تغییر کوچک","پچ"],
  ["path","n","a location in a filesystem or URL","مسیر","مسیر"],
  ["payload","n","the useful body of a message","بار مفید پیام","بار مفید"],
  ["peek","v","to look at the next item without removing it","نگاه به عنصر بعدی بدون برداشتن","نگاه کنید"],
  ["perf","n","performance work","بهینه‌سازی کارایی","پرف"],
  ["permission","n","a right granted to an identity","مجوز","مجوز"],
  ["persist","v","to save so it survives a restart","پایدار کردن داده","پایدار کنید"],
  ["PHP","n","a language often used for web backends","پی‌اچ‌پی","پی‌اچ‌پی"],
  ["pipeline","n","stages connected so output feeds the next input","خط لوله مراحل","پایپ‌لاین"],
  ["pixel","n","one dot of a digital image","پیکسل","پیکسل"],
  ["plain object","n","an object that is not a class instance","شیء ساده","شیء ساده"],
  ["plugin","n","an optional module that extends a host","افزونه","افزونه"],
  ["pointer","n","an address of a value in memory","اشاره‌گر","اشاره‌گر"],
  ["polyfill","n","code that implements a missing platform feature","پولی‌فیل","پولی‌فیل"],
  ["polymorphism","n","the same operation working on many types","چندریختی","چندریختی"],
  ["pool","n","a set of reusable connections or workers","استخر اتصال یا کارگر","استخر"],
  ["port","n","a numbered door on a host","پورت","پورت"],
  ["Postgres","n","a powerful open-source relational database","پستگرس","پستگرس"],
  ["pragma","n","a compiler hint in source","پراگما","پراگما"],
  ["Preact","n","a small React-compatible UI library","پریکت","پریکت"],
  ["predicate","n","a function that returns true or false","گزاره بولی","گزاره"],
  ["preload","v","to fetch something before it is needed","پیش‌بارگذاری","پیش‌بارگذاری کنید"],
  ["Prettier","n","an opinionated code formatter","پریتیر","پریتیر"],
  ["primitive","n","a basic built-in type","نوع اولیه","نوع اولیه"],
  ["Prisma","n","a TypeScript ORM","پریزما","پریزما"],
  ["private","adj","visible only inside a module or class","خصوصی","خصوصی"],
  ["process","n","a running program","فرایند","فرایند"],
  ["prod","n","the live production environment","محیط تولید","پرود"],
  ["profiler","n","a tool that measures where time is spent","پروفایلر","پروفایلر"],
  ["promise","n","an object representing a future value","پرامیس","پرامیس"],
  ["prompt","n","text sent to a language model; a CLI question","پرامپت مدل یا خط فرمان","پرامپت"],
  ["prop","n","data passed into a UI component","پراپ کامپوننت","پراپ"],
  ["protocol","n","agreed rules for talking on a network","پروتکل","پروتکل"],
  ["prototype","n","the object JavaScript uses for inheritance","پروتوتایپ","پروتوتایپ"],
  ["proxy","n","a stand-in that forwards requests","پروکسی","پروکسی"],
  ["pull request","n","a proposed git change for review","درخواست ادغام","پول ریکوئست"],
  ["pubsub","n","publish and subscribe messaging","انتشار و اشتراک","پاب‌ساب"],
  ["pull","v","to fetch commits from a remote","گرفتن کامیت از ریموت","پول کنید"],
  ["push","v","to send commits to a remote","ارسال کامیت به ریموت","پوش کنید"],
  ["Python","n","a popular general-purpose language","پایتون","پایتون"],
  ["QA","n","quality assurance","تضمین کیفیت","کیوا"],
  ["query","n","a request for data","پرس‌وجو","کوئری"],
  ["queue","n","a waiting line of jobs","صف","صف"],
  ["quicksort","n","a fast divide-and-conquer sort","مرتب‌سازی سریع","کوئیک‌سورت"],
  ["race condition","n","a bug that depends on lucky timing","شرایط رقابتی","ریس"],
  ["RAG","n","retrieval-augmented generation","تولید تقویت‌شده با بازیابی","رگ"],
  ["RAM","n","fast volatile memory","رم","رم"],
  ["rate limit","n","a cap on how often an API may be called","محدودیت نرخ فراخوانی","محدودیت نرخ"],
  ["RBAC","n","role-based access control","کنترل دسترسی مبتنی بر نقش","آربک"],
  ["React","n","a library for building user interfaces","ری‌اکت","ری‌اکت"],
  ["reactive","adj","updating automatically when data changes","واکنشی به تغییر داده","واکنشی"],
  ["readme","n","the first document in a repository","ریدمی","ریدمی"],
  ["rebase","v","to replay commits on another base","ریبیس کردن کامیت‌ها","ریبیس کنید"],
  ["record","n","a row of fields","رکورد","رکورد"],
  ["recursion","n","a function calling itself","بازگشت","بازگشت"],
  ["Redis","n","an in-memory data store","ردیس","ردیس"],
  ["Redux","n","a predictable state container","رداکس","رداکس"],
  ["refactor","v","to change structure without changing behavior","بازآرایی کد","بازآرایی کنید"],
  ["regex","n","a pattern language for matching text","عبارت منظم","ریجکس"],
  ["registry","n","a catalog of packages","رجیستری بسته","رجیستری"],
  ["release","n","a version shipped to users","انتشار","انتشار"],
  ["render","v","to produce UI from state","رندر کردن رابط","رندر کنید"],
  ["repo","n","a git repository","مخزن","ریپو"],
  ["request","n","a message asking a service for work","درخواست","درخواست"],
  ["resolve","v","to finish a promise; to find a module path","حل کردن پرامیس یا مسیر ماژول","حل کنید"],
  ["REST","n","an HTTP style of APIs using resources","رست","رست"],
  ["retry","v","to try an operation again after failure","تلاش مجدد","تلاش مجدد کنید"],
  ["return","v","to hand a value back from a function","برگرداندن مقدار","برگردانید"],
  ["reverse proxy","n","a server that sits in front of other servers","پروکسی معکوس","پروکسی معکوس"],
  ["RFC","n","a request for comments; a standards document","آراف‌سی","آراف‌سی"],
  ["ring buffer","n","a fixed-size queue that overwrites the oldest item","بافر حلقوی","بافر حلقوی"],
  ["rollback","v","to undo a deploy","بازگردانی استقرار","بازگردانید"],
  ["root","n","the top of a tree; the superuser","ریشه","ریشه"],
  ["router","n","code that maps URLs to pages","روتر","روتر"],
  ["RPC","n","remote procedure call","فراخوانی رویه از راه دور","آرسی"],
  ["Ruby","n","a dynamic object-oriented language","روبی","روبی"],
  ["runtime","n","the environment that executes a program","زمان اجرا","ران‌تایم"],
  ["Rust","n","a language focused on safety and speed","راست","راست"],
  ["S3","n","Amazon's object storage","اس۳","اس۳"],
  ["SaaS","n","software as a service","نرم‌افزار به‌عنوان سرویس","ساس"],
  ["sandbox","n","an isolated place to run untrusted code","سندباکس","سندباکس"],
  ["Sass","n","a CSS preprocessor","ساس برای سی‌اس‌اس","ساس"],
  ["scalar","n","a single number or string, not a collection","اسکالر","اسکالر"],
  ["scale","v","to handle more load","مقیاس‌پذیری","مقیاس دهید"],
  ["schema","n","the shape of data","طرح داده","اسکیما"],
  ["scope","n","the region where a name is visible","محدوده دید نام","اسکوپ"],
  ["script","n","a file of commands a runtime executes","اسکریپت","اسکریپت"],
  ["SDK","n","a software development kit","کیت توسعه نرم‌افزار","اس‌دی‌کی"],
  ["secret","n","a password or key that must stay private","راز پیکربندی","سکرت"],
  ["security","n","protecting systems from abuse","امنیت","امنیت"],
  ["seed","n","initial data; a value that starts a random generator","داده اولیه یا بذر تصادفی","سید"],
  ["segfault","n","a crash from an illegal memory access","خطای قطعه حافظه","سگفالت"],
  ["selector","n","a CSS pattern; a function that reads state","سلکتور","سلکتور"],
  ["semaphore","n","a counter that limits concurrent access","سمافور","سمافور"],
  ["serialize","v","to turn an object into bytes or text","سریالایز کردن","سریالایز کنید"],
  ["server","n","software that answers requests","سرور","سرور"],
  ["serverless","adj","running functions without managing hosts","بدون سرور اختصاصی","سرورلس"],
  ["service","n","a process that offers an API","سرویس","سرویس"],
  ["session","n","state kept for one visitor","نشست کاربر","سشن"],
  ["set","n","a collection of unique values","مجموعه یکتا","ست"],
  ["SHA","n","a family of cryptographic hash functions","شا","شا"],
  ["shadow DOM","n","an encapsulated DOM tree inside an element","شadow دام محصور","شadow دام"],
  ["shallow copy","n","a clone that shares nested references","کپی سطحی","کپی سطحی"],
  ["shard","n","one slice of a split dataset","شارد داده","شارد"],
  ["shell","n","a program that runs commands","پوسته فرمان","شل"],
  ["ship","v","to release to users","انتشار برای کاربر","شیپ کنید"],
  ["sidecar","n","a helper container next to the main one","سایدکار","سایدکار"],
  ["SIMD","n","one instruction on many data lanes","سیمد","سیمد"],
  ["singleton","n","a type with only one instance","تک‌نمونه","سینگلتون"],
  ["SLA","n","a service-level agreement","توافق سطح خدمت","اس‌ال‌ای"],
  ["slug","n","a URL-safe short name","نامک نشانی","اسلاگ"],
  ["SMTP","n","the protocol for sending email","اس‌ام‌تی‌پی","اس‌ام‌تی‌پی"],
  ["snake_case","n","a naming style like this_word_here","نام‌گذاری ماری","ماری"],
  ["snapshot","n","a frozen copy of state","اسنپ‌شات","اسنپ‌شات"],
  ["SOAP","n","an XML web-service protocol","سوپ","سوپ"],
  ["socket","n","an endpoint for network communication","سوکت","سوکت"],
  ["SOLID","n","five object-oriented design principles","اصول سالید","سالید"],
  ["source map","n","a file mapping minified code back to source","سورس‌مپ","سورس‌مپ"],
  ["SPA","n","a single-page application","اپ تک‌صفحه‌ای","اس‌پی‌ای"],
  ["spawn","v","to start a child process","ایجاد فرایند فرزند","اسپان کنید"],
  ["spec","n","a precise description of behavior","مشخصات","اسپک"],
  ["spike","n","a short experiment in code","آزمایش کوتاه کد","اسپایک"],
  ["SQL","n","the language of relational databases","اس‌کیوال","اس‌کیوال"],
  ["SQLite","n","an embedded SQL database","اس‌کیو‌لایت","اس‌کیو‌لایت"],
  ["SSH","n","a secure remote shell","اس‌اس‌اچ","اس‌اس‌اچ"],
  ["SSL","n","an older name for TLS","اس‌اس‌ال","اس‌اس‌ال"],
  ["SSO","n","single sign-on","ورود یکپارچه","اس‌اس‌او"],
  ["stack","n","last-in first-out storage; the technologies you use","پشته؛ یا مجموعه فناوری","استک"],
  ["staging","n","an environment that mirrors production","محیط آزمایشی نزدیک تولید","استیجینگ"],
  ["standard library","n","the modules that ship with a language","کتابخانه استاندارد","کتابخانه استاندارد"],
  ["state","n","data that changes over time in a UI","وضعیت رابط","استیت"],
  ["static","adj","known at compile time; files served as-is","ایستا","ایستا"],
  ["stdin","n","the standard input stream","ورودی استاندارد","استدی‌این"],
  ["stdout","n","the standard output stream","خروجی استاندارد","استدی‌اوت"],
  ["storage","n","a place that keeps bytes","ذخیره‌سازی","استوریج"],
  ["stream","n","data that arrives over time","جریان داده","استریم"],
  ["string","n","a sequence of characters","رشته","رشته"],
  ["struct","n","a composite value with named fields","استراکت","استراکت"],
  ["stub","n","a tiny fake with canned answers","استاب تست","استاب"],
  ["stylesheet","n","a file of CSS rules","برگه استایل","استایل‌شیت"],
  ["subprocess","n","a child process","فرایند فرزند","ساب‌پروسس"],
  ["sudo","n","a command that runs as another user","سودو","سودو"],
  ["Supabase","n","an open Firebase alternative","سوپابیس","سوپابیس"],
  ["SVG","n","scalable vector graphics","اس‌وی‌جی","اس‌وی‌جی"],
  ["Swagger","n","tools around the OpenAPI spec","سوگر","سوگر"],
  ["Swift","n","Apple's language for apps","سوئیفت","سوئیفت"],
  ["switch","n","a multi-way branch; a network device","سوئیچ","سوئیچ"],
  ["symlink","n","a filesystem pointer to another path","پیوند نمادین","سیم‌لینک"],
  ["syntax","n","the grammar of a language","نحو","نحو"],
  ["systemd","n","the service manager on many Linux systems","سیستم‌دی","سیستم‌دی"],
  ["table","n","rows and columns of data","جدول","جدول"],
  ["tag","n","a label on a commit or an HTML element","برچسب","تگ"],
  ["Tailwind","n","a utility-first CSS framework","تیلویند","تیلویند"],
  ["TanStack","n","a suite of headless React libraries","تن‌استک","تن‌استک"],
  ["TDD","n","test-driven development","توسعه آزمون‌محور","تی‌دی‌دی"],
  ["TCP","n","a reliable stream protocol","تی‌سی‌پی","تی‌سی‌پی"],
  ["template","n","text with holes filled at runtime","قالب","تمپلیت"],
  ["terminal","n","a text interface to a computer","ترمینال","ترمینال"],
  ["test","n","code that checks other code","تست","تست"],
  ["theme","n","a set of visual tokens","تم بصری","تم"],
  ["thread","n","a line of execution inside a process","نخ اجرا","ترد"],
  ["throttle","v","to cap how often a function runs","محدود کردن نرخ اجرا","تروتل کنید"],
  ["throw","v","to raise an exception","پرتاب استثنا","پرتاب کنید"],
  ["timeout","n","a limit on how long to wait","مهلت انتظار","تایم‌اوت"],
  ["TLS","n","transport layer security","تی‌ال‌اس","تی‌ال‌اس"],
  ["TODO","n","a marker for unfinished work","یادداشت کار ناتمام","تودو"],
  ["token","n","a lexeme; a secret string; an LLM unit of text","توکن","توکن"],
  ["toolchain","n","the compilers and tools used to build","زنجیره ابزار ساخت","تولچین"],
  ["tooltip","n","a small hover hint","نکته شناور","تولتیپ"],
  ["transaction","n","a group of writes that all succeed or all fail","تراکنش","تراکنش"],
  ["transpile","v","to compile from one high-level language to another","ترنسپایل کردن","ترنسپایل کنید"],
  ["tree","n","a hierarchy of nodes","درخت","درخت"],
  ["tree-shaking","n","dropping unused exports from a bundle","حذف صادرات استفاده‌نشده","تری‌شیکینگ"],
  ["trigger","n","an event that starts a job","محرک کار","تریگر"],
  ["try/catch","n","syntax for handling exceptions","ترای‌کچ","ترای‌کچ"],
  ["TTL","n","time to live for a cached item","عمر کش","تی‌تی‌ال"],
  ["tuple","n","a fixed-length sequence of values","تاپل","تاپل"],
  ["Turbo","n","a fast JS bundler and monorepo tool","توربو","توربو"],
  ["type","n","a description of allowed values","نوع","تایپ"],
  ["TypeScript","n","JavaScript with types","تایپ‌اسکریپت","تایپ‌اسکریپت"],
  ["UI","n","user interface","رابط کاربری","یوآی"],
  ["UDP","n","a lightweight datagram protocol","یو‌دی‌پی","یو‌دی‌پی"],
  ["UML","n","a set of diagrams for software design","یو‌ام‌ال","یو‌ام‌ال"],
  ["undefined","n","a JavaScript value meaning no value was set","آندیفایند","آندیفایند"],
  ["union","n","a type that can be one of several options","نوع اجتماع","یونیون"],
  ["unit test","n","a test of a small isolated piece","تست واحد","تست واحد"],
  ["Unix","n","a family of operating systems","یونیکس","یونیکس"],
  ["unmount","v","to remove a component from the tree","پیاده کردن کامپوننت","آن‌ماونت کنید"],
  ["unwrap","v","to take the inner value out of a wrapper","بیرون آوردن مقدار درونی","آن‌رپ کنید"],
  ["upsert","v","to insert or update if the row exists","آپ‌سرت","آپ‌سرت کنید"],
  ["URI","n","a uniform resource identifier","یو‌آر‌آی","یو‌آر‌آی"],
  ["URL","n","a web address","نشانی وب","یو‌آر‌ال"],
  ["UTC","n","coordinated universal time","یو‌تی‌سی","یو‌تی‌سی"],
  ["UTF-8","n","a Unicode encoding used on the web","یوتی‌اف۸","یوتی‌اف۸"],
  ["UUID","n","a 128-bit unique identifier","شناسه یکتا","یو‌یو‌آی‌دی"],
  ["UX","n","user experience","تجربه کاربری","یواکس"],
  ["V8","n","the JavaScript engine in Chrome and Node","وی۸","وی۸"],
  ["validate","v","to check that data meets rules","اعتبارسنجی کردن","اعتبارسنجی کنید"],
  ["variable","n","a named place that holds a value","متغیر","متغیر"],
  ["virtual DOM","n","an in-memory tree used to update the real DOM cheaply","دام مجازی","دام مجازی"],
  ["vector","n","an array of numbers; an embedding","بردار","بردار"],
  ["Vercel","n","a platform for frontend deploys","ورسل","ورسل"],
  ["version","n","a labeled snapshot of software","نسخه","ورژن"],
  ["viewport","n","the visible area of a page","ویوپورت","ویوپورت"],
  ["Vim","n","a modal text editor","ویم","ویم"],
  ["virtual","adj","simulated rather than physical","مجازی","مجازی"],
  ["Vite","n","a fast frontend build tool","ویت","ویت"],
  ["VM","n","a virtual machine","ماشین مجازی","وی‌ام"],
  ["void","n","a type meaning no useful value is returned","نوع تهی","وید"],
  ["VPN","n","a virtual private network","وی‌پی‌ان","وی‌پی‌ان"],
  ["VS Code","n","a popular code editor","وی‌اس‌کد","وی‌اس‌کد"],
  ["Vue","n","a progressive UI framework","ویو","ویو"],
  ["WAF","n","a web application firewall","فایروال برنامه وب","واف"],
  ["WASM","n","WebAssembly","وب‌اسمبلی","واسم"],
  ["webhook","n","an HTTP callback when an event happens","وب‌هوک","وب‌هوک"],
  ["webpack","n","a JavaScript module bundler","وب‌پک","وب‌پک"],
  ["WebSocket","n","a full-duplex socket over HTTP","وب‌سوکت","وب‌سوکت"],
  ["widget","n","a small reusable UI control","ویجت","ویجت"],
  ["wildcard","n","a symbol that matches anything","نویسه عام","وایلدکارد"],
  ["window","n","the global object in a browser","شیء پنجره مرورگر","ویندو"],
  ["worker","n","a background thread or process","ورکر","ورکر"],
  ["workflow","n","a sequence of automated steps","گردش کار","ورک‌فلو"],
  ["workspace","n","a folder of related packages","فضای کار","ورک‌اسپیس"],
  ["wrapper","n","a thin layer around another API","پوشش نازک روی ای‌پی‌آی","رپر"],
  ["WSL","n","Windows Subsystem for Linux","زیرسیستم لینوکس در ویندوز","دبلیو‌اس‌ال"],
  ["XHR","n","XMLHttpRequest, the old AJAX API","ایکس‌اچ‌آر","ایکس‌اچ‌آر"],
  ["XML","n","a tagged markup language","ایکس‌ام‌ال","ایکس‌ام‌ال"],
  ["XSS","n","cross-site scripting","اسکریپت بین‌سایتی","ایکس‌اس‌اس"],
  ["YAML","n","a whitespace-sensitive config language","یمل","یمل"],
  ["Yarn","n","a JavaScript package manager","یارن","یارن"],
  ["YAGNI","n","you aren't gonna need it","اصل نساختن ویژگی زودتر از نیاز","یاگنی"],
  ["yield","v","to pause a generator and return a value","توقف مولد و بازگرداندن مقدار","یلد کنید"],
  ["zero-downtime","adj","updating without users seeing an outage","بدون قطعی برای کاربر","بدون قطعی"],
  ["Zig","n","a systems language with manual memory control","زیگ","زیگ"],
  ["zip","n","an archive format; pairing two lists","زیپ","زیپ"],
  ["Zustand","n","a small React state library","زوستند","زوستند"],
  ["zombie process","n","a dead child still listed by the parent","فرایند زامبی","زامبی"],
  ["vibe coding","n","building by steering an AI instead of typing every line","وایب‌کدینگ؛ ساخت با هدایت هوش مصنوعی","وایب‌کدینگ"],
  ["copilot","n","an AI assistant inside the editor","هم‌خلبان هوش مصنوعی در ادیتور","کوپایلوت"],
  ["prompt engineering","n","crafting inputs so a model answers well","مهندسی پرامپت","مهندسی پرامپت"],
  ["hallucination","n","a fluent but false model answer","توهم مدل زبانی","توهم"],
  ["context window","n","how much text a model can see at once","پنجره بافت مدل","پنجره بافت"],
  ["agent","n","software that calls tools to finish a goal","عامل نرم‌افزاری","ایجنت"],
  ["tool call","n","a model request to run a named function","فراخوانی ابزار توسط مدل","تول‌کال"],
  ["embedding","n","a vector that represents meaning","امبدینگ معنایی","امبدینگ"],
  ["vector database","n","storage optimized for similarity search","پایگاه بردار","پایگاه بردار"],
  ["fine-tune","v","to train a model further on your data","تنظیم ظریف مدل","فاین‌تیون کنید"],
  ["LoRA","n","low-rank adapters for cheaper fine-tuning","لورا؛ آداپتور کم‌رتبه","لورا"],
  ["temperature","n","a knob that controls randomness of model output","دمای نمونه‌برداری مدل","دما"],
  ["system prompt","n","hidden instructions that steer a model","پرامپت سیستم","پرامپت سیستم"],
  ["checkpoint","n","saved model weights at a training step","چک‌پوینت وزن مدل","چک‌پوینت"],
  ["weights","n","the numbers a neural net learned","وزن‌های شبکه عصبی","وزن"],
  ["few-shot","n","showing a model a handful of examples in the prompt","چندنمونه در پرامپت","فیوشات"],
  ["zero-shot","n","asking a model with no examples","بدون نمونه در پرامپت","زیرو‌شات"],
  ["chain of thought","n","asking a model to reason step by step","زنجیره فکر","چین‌آو‌تات"],
  ["agentic","adj","able to plan and use tools toward a goal","عامل‌گونه","ایجنتیک"],
  ["eval","n","a scored test of model quality","ارزیابی مدل","ایول"],
  ["dataset","n","examples used to train or test","مجموعه داده","دیتاست"],
  ["RLHF","n","reinforcement learning from human feedback","یادگیری تقویتی از بازخورد انسان","آرال‌اچ‌اف"],
  ["alignment","n","making a model follow human intent","هم‌راستایی مدل با نیت انسان","الاینمنت"],
  ["MCP","n","model context protocol for tools","پروتکل بافت مدل","ام‌سی‌پی"],
  ["Cursor","n","an AI-first code editor","ادیتور کرسر","کرسر"],
  ["LLM","n","a large language model","مدل زبانی بزرگ","ال‌ال‌ام"],
  ["transformer","n","the neural architecture behind modern LLMs","ترانسفورمر","ترانسفورمر"],
  ["attention","n","a mechanism that weights tokens by relevance","توجه در شبکه","توجه"],
  ["tokenizer","n","the step that splits text into model tokens","توکنایزر","توکنایزر"],
  ["streaming","n","sending tokens as they are generated","جریان توکن‌ها","استریمینگ"],
  ["function calling","n","letting a model pick a tool and arguments","فراخوانی تابع توسط مدل","فانکشن‌کالینگ"],
  ["Grok","n","xAI's assistant and model family","گرک","گرک"],
  ["OpenAPI","n","a standard for describing HTTP APIs","اوپن‌ای‌پی‌آی","اوپن‌ای‌پی‌آی"],
  ["Webhooks","n","HTTP callbacks fired by events","وب‌هوک‌ها","وب‌هوک"],
  ["observability","n","logs, metrics, and traces that explain a live system","مشاهده‌پذیری سیستم","آبزروبیلیتی"],
  ["tracing","n","following a request across services","ردیابی درخواست","تریس"],
  ["span","n","one timed step inside a trace","اسپن در تریس","اسپن"],
  ["structured logging","n","logs as fields, not free text","لاگ ساخت‌یافته","لاگ ساخت‌یافته"],
  ["feature freeze","n","a period when only fixes may land","توقف ویژگی جدید","فریز ویژگی"],
  ["hotfix train","n","a rapid path for urgent production fixes","قطار رفع فوری","قطار هات‌فیکس"],
  ["on-call","n","the rotation that answers incidents","کشیک حادثه","آن‌کال"],
  ["incident","n","an unplanned production problem","حادثه تولید","اینسیدنت"],
  ["postmortem","n","a write-up of what broke and how to stop a repeat","گزارش پس از حادثه","پست‌مورتم"],
  ["runbook","n","step-by-step ops instructions","ران‌بوک عملیاتی","ران‌بوک"],
  ["playbook","n","a prepared response for a class of incident","راهنمای واکنش","پلی‌بوک"],
  ["SLO","n","a service-level objective","هدف سطح خدمت","اس‌ال‌او"],
  ["error budget","n","how much unreliability you can spend","بودجه خطا","بودجه خطا"],
  ["toil","n","manual repetitive ops work","کار تکراری عملیاتی","تویل"],
  ["pager","n","an alert that wakes the on-call","پیجر هشدار","پیجر"],
  ["war room","n","a temporary channel for fighting an outage","اتاق جنگ قطعی","وار روم"],
  ["blast radius","n","how much a failure can touch","شعاع آسیب","شعاع آسیب"],
  ["graceful degradation","n","staying useful when a dependency dies","افت نرم کیفیت","افت نرم"],
  ["circuit breaking","n","cutting off a sick dependency","قطع مدار وابستگی بیمار","قطع مدار"],
  ["bulkhead","n","isolating failures so they cannot flood the ship","دیواره جداساز خرابی","بالک‌هد"],
  ["retry storm","n","clients retrying so hard they worsen an outage","طوفان تلاش مجدد","طوفان ریترای"],
  ["jitter","n","random delay added to retries","تأخیر تصادفی ریترای","جیتر"],
  ["exponential backoff","n","waiting longer after each failed try","عقب‌نشینی نمایی","بک‌آف نمایی"],
  ["idempotency key","n","a client token that makes retries safe","کلید ایدمپوتنسی","کلید ایدمپوتنسی"],
  ["exactly once","n","a delivery claim that is hard to keep on a network","تحویل دقیقاً یک‌بار","دقیقاً یک‌بار"],
  ["at-least-once","n","delivery that may duplicate","حداقل یک‌بار","حداقل یک‌بار"],
  ["at-most-once","n","delivery that may drop","حداکثر یک‌بار","حداکثر یک‌بار"],
  ["eventual consistency","n","replicas that agree after a delay","سازگاری نهایی","سازگاری نهایی"],
  ["strong consistency","n","reads that always see the latest write","سازگاری قوی","سازگاری قوی"],
  ["linearizability","n","the strictest real-time consistency model","خطی‌سازی","لینیارایز"],
  ["quorum","n","a majority of replicas that must agree","حدنصاب replica","کورم"],
  ["Raft","n","a consensus algorithm","رفت؛ الگوریتم اجماع","رفت"],
  ["Paxos","n","a classic consensus protocol","پکسوس","پکسوس"],
  ["gossip","n","peers sharing state in a random mesh","شایعه پراکنی وضعیت","گاسیپ"],
  ["CRDT","n","a type that merges without coordination","سی‌آردی‌تی","سی‌آردی‌تی"],
  ["vector clock","n","a stamp that orders events across nodes","ساعت برداری","ساعت برداری"],
  ["Merkle tree","n","a hash tree used to compare large sets","درخت مرکل","درخت مرکل"],
  ["LSM tree","n","a log-structured merge tree for writes","درخت ال‌اس‌ام","ال‌اس‌ام"],
  ["WAL","n","a write-ahead log","لاگ پیش از نوشتن","وال"],
  ["B+ tree","n","a tree of sorted keys used by databases","بی‌پلاس‌تری","بی‌پلاس"],
  ["inverted index","n","a map from terms to documents","ایندکس وارونه","ایندکس وارونه"],
  ["full-text","n","search across the words in documents","جستجوی تمام‌متن","فول‌تکست"],
  ["stemming","n","reducing words to a common stem","ریشه‌یابی واژه","استمینگ"],
  ["n-gram","n","a sequence of n tokens","ان‌گرام","ان‌گرام"],
  ["cosine similarity","n","a measure of how close two vectors point","شباهت کسینوسی","کسینوس"],
  ["k-NN","n","k nearest neighbors search","کی‌ان‌ان","کی‌ان‌ان"],
  ["HNSW","n","a graph index for approximate nearest neighbors","اچ‌ان‌اس‌دبلیو","اچ‌ان‌اس‌دبلیو"],
  ["ANN","n","approximate nearest neighbor search","جستجوی همسایه تقریبی","ای‌ان‌ان"],
  ["quantization","n","storing numbers with fewer bits","کوانتیزه کردن اعداد","کوانتیزه"],
  ["distillation","n","training a small model to copy a large one","تقطیر مدل","دیستیل"],
  ["mixture of experts","n","a model that routes tokens to specialist nets","مخلوط خبره‌ها","موئی"],
  ["MoE","n","mixture of experts","مخلوط متخصصان","ام‌او‌ای"],
  ["KV cache","n","stored attention keys and values during generation","کش کلید-مقدار توجه","کش کی‌وی"],
  ["speculative decoding","n","drafting tokens with a small model then verifying","رمزگشایی حدسی","اسپکیولیتیو"],
  ["guardrail","n","a filter that blocks unsafe model output","نرده ایمنی مدل","گاردریل"],
  ["eval harness","n","the scaffolding that runs model tests","هارنس ارزیابی","هارنس"],
  ["golden file","n","a checked-in expected output for tests","فایل طلایی تست","گلدن فایل"],
  ["snapshot test","n","a test that compares against last output","تست اسنپ‌شات","تست اسنپ‌شات"],
  ["contract test","n","a test that two services still agree on a schema","تست قرارداد","تست کانترکت"],
  ["smoke test","n","a shallow check that the app starts and renders","تست دود","اسموک تست"],
  ["e2e","n","an end-to-end test through the real UI","تست سرتاسری","ای۲ای"],
  ["flaky test","n","a test whose result is not stable","تست ناپایدار","تست فلیکی"],
  ["test double","n","any fake used in place of a real collaborator","جایگزین تست","تست‌دابل"],
  ["spy","n","a test double that records calls","اسپای تست","اسپای"],
  ["fake","n","a working but simplified stand-in","فیک ساده","فیک"],
  ["arrange-act-assert","n","a three-step shape for a unit test","چیدمان-عمل-ادعا","تریپل ای"],
  ["given-when-then","n","the BDD shape of a scenario","با‌فرض-وقتی-آنگاه","گیون‌ون‌دن"],
  ["page object","n","a test helper that wraps a screen","شیء صفحه تست","پیج آبجکت"],
  ["Playwright","n","a browser automation library","پلی‌رایت","پلی‌رایت"],
  ["Cypress","n","an in-browser end-to-end runner","سایپرس","سایپرس"],
  ["Vitest","n","a Vite-native test runner","ویتست","ویتست"],
  ["coverage","n","how much source a test suite executes","پوشش تست","کاورج"],
  ["mutation testing","n","checking that tests fail when code is broken on purpose","تست جهش","میوتیشن"],
  ["property test","n","a test that checks a rule on many random inputs","تست ویژگی","پراپرتی تست"],
  ["fuzz test","n","a test that hammers an API with junk","تست فاز","فاز تست"],
  ["load test","n","a test of behavior under heavy traffic","تست بار","لود تست"],
  ["soak test","n","a long run that hunts leaks","تست خیساندن","سوک تست"],
  ["chaos engineering","n","breaking things on purpose to learn","مهندسی آشوب","آشوب"],
  ["game day","n","a planned rehearsal of failure","روز تمرین حادثه","گیم‌دی"],
  ["dark launch","n","shipping code that is off for most users","انتشار تاریک","دارک لانچ"],
  ["feature toggle","n","another name for a feature flag","کلید ویژگی","تاگل ویژگی"],
  ["trunk based","n","shipping to one main branch in small steps","توسعه روی تنه اصلی","ترانک"],
  ["gitflow","n","a branching model with develop and release lanes","گیت‌فلو","گیت‌فلو"],
  ["conventional commits","n","commit messages with a typed prefix","کامیت قراردادی","کانونشنال"],
  ["semver","n","major.minor.patch version numbers","نسخه‌گذاری معنایی","سم‌ور"],
  ["changelog","n","a human list of what changed","گزارش تغییرات","چنج‌لاگ"],
  ["release notes","n","user-facing text for a version","یادداشت انتشار","ریلیز نوت"],
  ["canary analysis","n","comparing a small rollout to the baseline","تحلیل قناری","آنالیز قناری"],
  ["progressive delivery","n","rolling out to more users as confidence grows","تحویل تدریجی","پروگرسیو"],
  ["feature store","n","a catalog of ML features for training and serving","فروشگاه ویژگی یادگیری","فیچر استور"],
  ["training job","n","a batch that updates model weights","کار آموزش مدل","ترینینگ جاب"],
  ["inference server","n","a process that answers model queries","سرور استنتاج","اینفرنس سرور"],
  ["batch inference","n","scoring many rows offline","استنتاج دسته‌ای","بتچ اینفرنس"],
  ["online inference","n","scoring one request at a time","استنتاج برخط","آنلاین اینفرنس"],
  ["feature leakage","n","training on data you would not have at predict time","نشت ویژگی","لیکیج"],
  ["data drift","n","live inputs moving away from the training set","رانش داده","دریفت"],
  ["concept drift","n","the meaning of labels changing over time","رانش مفهوم","کانسپت دریفت"],
  ["ground truth","n","the labeled answers you treat as correct","حقیقت مبنا","گراند تروث"],
  ["human in the loop","n","a person who reviews or labels model work","انسان در حلقه","هیومن این د لوپ"],
  ["rubric","n","a scoring guide for subjective answers","روبریک نمره‌دهی","روبریک"],
  ["pref","n","a human preference between two answers","ترجیح انسانی","پرف"],
  ["SFT","n","supervised fine-tuning","تنظیم نظارتی","اس‌اف‌تی"],
  ["DPO","n","direct preference optimization","بهینه‌سازی مستقیم ترجیح","دی‌پی‌او"],
  ["quantized model","n","weights stored with fewer bits","مدل کوانتیزه","مدل کوانتیزه"],
  ["GGUF","n","a file format for local LLM weights","فرمت جی‌جی‌یواف","جی‌جی‌یواف"],
  ["Ollama","n","a local runner for open models","اولاما","اولاما"],
  ["vLLM","n","a high-throughput inference engine","وی‌ال‌ال‌ام","وی‌ال‌ال‌ام"],
  ["OpenRouter","n","a gateway to many model APIs","اوپن‌روتر","اوپن‌روتر"],
  ["Groq","n","an inference company with fast LPUs","گراک اینفرنس","گراک"],
  ["token budget","n","how many tokens you can afford to spend","بودجه توکن","بودجه توکن"],
  ["max tokens","n","a cap on generated length","سقف توکن خروجی","مکس توکن"],
  ["stop sequence","n","text that tells the model to halt","دنباله توقف","استاپ سیکوئنس"],
  ["logit bias","n","a knob that favors or blocks tokens","بایاس لاجیت","لاجیت بایاس"],
  ["top-p","n","nucleus sampling of likely tokens","نمونه‌برداری هسته‌ای","تاپ‌پی"],
  ["top-k","n","sampling from the k most likely tokens","نمونه‌برداری از کی محتمل","تاپ‌کی"],
  ["repetition penalty","n","a bias against repeating tokens","جریمه تکرار","پنالتی تکرار"],
  ["JSON mode","n","asking a model to emit valid JSON only","حالت جیسون","جیسون مود"],
  ["structured output","n","model replies that match a schema","خروجی ساخت‌یافته","استراکچرد آوت‌پوت"],
  ["tool schema","n","the JSON description of a callable function","طرح ابزار","تول اسکیما"],
  ["multi-agent","n","several agents that hand work to each other","چندعاملی","مالتی‌ایجنت"],
  ["planner","n","an agent that breaks a goal into steps","برنامه‌ریز","پلنر"],
  ["critic","n","an agent that reviews another agent's work","منتقد عامل","کریتیک"],
  ["sandbox escape","n","untrusted code breaking its isolation","فرار از سندباکس","سندباکس اسکیپ"],
  ["prompt injection","n","hostile text that hijacks a model's instructions","تزریق پرامپت","پرامپت اینجکشن"],
  ["exfiltration","n","stealing data out of a system","خروج پنهان داده","اکس‌فیل"],
  ["least privilege","n","granting only the access that is needed","حداقل دسترسی لازم","لیست پریویلیج"],
  ["defense in depth","n","several layers of controls","دفاع چندلایه","دیفنس این دپث"],
  ["threat model","n","a map of who might attack and how","مدل تهدید","ترت مدل"],
  ["SBOM","n","a software bill of materials","صورت مواد نرم‌افزار","اس‌بام"],
  ["supply chain","n","the path from dependencies to your build","زنجیره تأمین","ساپلای چین"],
  ["pinning","n","locking a dependency to an exact version","قفل نسخه وابستگی","پینینگ"],
  ["lockfile","n","the exact resolved set of packages","فایل قفل وابستگی","لاک‌فایل"],
  ["semver range","n","a pattern of acceptable versions","بازه نسخه معنایی","رنج سم‌ور"],
  ["peer dependency","n","a package the host is expected to provide","وابستگی همتا","پیر دپ"],
  ["tree of deps","n","the graph of packages you install","درخت وابستگی","تری دپس"],
  ["hoisting","n","lifting packages to a shared node_modules","بالا کشیدن بسته","هویستینگ"],
  ["pnpm","n","a content-addressed Node package manager","پی‌ان‌پی‌ام","پی‌ان‌پی‌ام"],
  ["Bun","n","a fast JavaScript runtime and toolkit","بان","بان"],
  ["Deno","n","a secure TypeScript runtime","دینو","دینو"],
  ["esbuild","n","an extremely fast JS bundler","ای‌اس‌بیلد","ای‌اس‌بیلد"],
  ["SWC","n","a Rust-based JS/TS compiler","اس‌دبلیوسی","اس‌دبلیوسی"],
  ["Rolldown","n","a Rust bundler aimed at Vite","رول‌داون","رول‌داون"],
  ["Nitro","n","a server toolkit used by TanStack Start","نیترو","نیترو"],
  ["TanStack Start","n","a full-stack React framework","تن‌استک استارت","تن‌استک استارت"],
  ["TanStack Router","n","a type-safe React router","تن‌استک روتر","تن‌استک روتر"],
  ["TanStack Query","n","async state for server data","تن‌استک کوئری","تن‌استک کوئری"],
  ["server function","n","RPC from the client to trusted server code","تابع سرور","سرور فانکشن"],
  ["loader","n","a function that loads data for a route","لودر مسیر","لودر"],
  ["action","n","a function that mutates data from a form","اکشن فرم","اکشن"],
  ["SSR","n","server-side rendering","رندر سمت سرور","اس‌اس‌آر"],
  ["SSG","n","static site generation","تولید سایت ایستا","اس‌اس‌جی"],
  ["ISR","n","incremental static regeneration","بازتولید ایستای تدریجی","آی‌اس‌آر"],
  ["PPR","n","partial prerendering","پیش‌رندر جزئی","پی‌پی‌آر"],
  ["RSC","n","React server components","کامپوننت سرور ری‌اکت","آرسی"],
  ["hydration mismatch","n","server HTML that does not match the client","عدم تطابق هیدریشن","میسمچ"],
  ["use client","n","a directive that marks a React Client Component","دستور یوز کلاینت","یوز کلاینت"],
  ["use server","n","a directive that marks server actions","دستور یوز سرور","یوز سرور"],
  ["edge runtime","n","a slim JS runtime at CDN locations","ران‌تایم لبه","اج ران‌تایم"],
  ["cold start","n","the delay when a sleeping function wakes","شروع سرد","کلد استارت"],
  ["warm start","n","a reuse of an already loaded worker","شروع گرم","وارم استارت"],
  ["scale to zero","n","shutting idle compute so you pay nothing","مقیاس تا صفر","اسکیل تو زیرو"],
  ["provisioned concurrency","n","keeping workers warm on purpose","همزمانی ازپیش‌آماده‌شده","پروویژند"],
  ["region","n","a data-center location","منطقه دیتاسنتر","ریجن"],
  ["multi-region","adj","running in more than one location","چندمنطقه‌ای","مالتی‌ریجن"],
  ["active-active","adj","serving traffic in several regions at once","فعال-فعال","اکتیو اکتیو"],
  ["active-passive","adj","a hot primary and a standing backup","فعال-منفعل","اکتیو پسیو"],
  ["RPO","n","how much data you can afford to lose","هدف نقطه بازیابی","آپی‌او"],
  ["RTO","n","how quickly you must be back","هدف زمان بازیابی","آرتی‌او"],
  ["backup window","n","the time you take a consistent copy","پنجره پشتیبان","بکاپ ویندو"],
  ["point in time recovery","n","restoring to a chosen moment","بازیابی نقطه‌ای در زمان","پی‌آی‌تی‌آر"],
  ["logical replication","n","copying row changes to another database","تکثیر منطقی","ریپلیکیشن منطقی"],
  ["physical replication","n","copying the database files themselves","تکثیر فیزیکی","ریپلیکیشن فیزیکی"],
  ["read replica","n","a copy that serves reads","رپلیکای خواندن","رید رپلیکا"],
  ["write amplification","n","extra writes caused by storage internals","تشدید نوشتن","رایت امپ"],
  ["compaction","n","rewriting files to reclaim space","فشرده‌سازی فایل‌های ذخیره","کامپکشن"],
  ["vacuum","n","Postgres cleanup of dead row versions","وکوم پستگرس","وکوم"],
  ["autovacuum","n","Postgres cleaning itself in the background","اتووکوم","اتووکوم"],
  ["connection pooler","n","a proxy that multiplexes database clients","ادغام‌کننده اتصال","پولر"],
  ["prepared statement","n","a query parsed once and run many times","دستور آماده‌شده","پرپیر استیتمنت"],
  ["explain plan","n","the database's chosen strategy for a query","طرح اجرا","اکسپلین"],
  ["seq scan","n","reading a table from start to finish","اسکن ترتیبی جدول","سک اسکن"],
  ["index scan","n","finding rows through an index","اسکن ایندکس","ایندکس اسکن"],
  ["bitmap scan","n","combining indexes then visiting the heap","اسکن بیت‌مپ","بیت‌مپ اسکن"],
  ["nested loop","n","a join that probes the inner table per outer row","حلقه تودرتو جوین","نستد لوپ"],
  ["hash join","n","a join that builds a hash table of one side","جوین هش","هش جوین"],
  ["merge join","n","a join of two already sorted inputs","جوین ادغامی","مرج جوین"],
  ["covering index","n","an index that can answer a query without the table","ایندکس پوششی","کاوریگ ایندکس"],
  ["partial index","n","an index on a subset of rows","ایندکس جزئی","پارشیال ایندکس"],
  ["expression index","n","an index on a computed value","ایندکس عبارت","اکسپرشن ایندکس"],
  ["GIN","n","a Postgres index for composite values","ایندکس جین","جین"],
  ["GiST","n","a Postgres index for geometric and full-text","ایندکس جی‌آی‌اس‌تی","جیست"],
  ["BRIN","n","a tiny index for naturally ordered columns","ایندکس برین","برین"],
  ["TOAST","n","Postgres storage for oversized values","توست پستگرس","توست"],
  ["MVCC","n","multi-version concurrency control","کنترل همزمانی چندنسخه‌ای","ام‌وی‌سی‌سی"],
  ["isolation level","n","how much one transaction sees of another","سطح انزوا","آیزولیشن"],
  ["dirty read","n","seeing another transaction's uncommitted write","خواندن کثیف","دیرتی رید"],
  ["nonrepeatable read","n","seeing a different value on a later read","خواندن تکرارناپذیر","نان‌ریپیتبل"],
  ["phantom read","n","seeing new rows appear in a later read","خواندن شبح","فانتوم رید"],
  ["serialization anomaly","n","a result that could not happen in serial order","ناهنجاری سریال","سریالیزیشن"],
  ["two-phase commit","n","a protocol that commits across nodes together","تعهد دوفازی","تو‌فاز"],
  ["saga","n","a sequence of local transactions with compensations","ساگا","ساگا"],
  ["outbox","n","a table of events to publish reliably","جدول اوت‌باکس","اوت‌باکس"],
  ["inbox","n","a table of received events to make handling unique","جدول این‌باکس","این‌باکس"],
  ["dead letter","n","a queue for messages that failed too often","نامه مرده","دد لتر"],
  ["poison pill","n","a message that always crashes a consumer","پیام سمی","پویزن پیل"],
  ["backfill","n","replaying history into a new store","بازپرکردن داده","بک‌فیل"],
  ["cutover","n","the moment traffic moves to the new system","قطع و انتقال ترافیک","کات‌اوور"],
  ["dual write","n","writing to old and new stores at once","نوشتن دوگانه","دوال رایت"],
  ["strangler fig","n","replacing a legacy system piece by piece","الگوی درخت خفه‌کننده","استرنگلر"],
  ["anti-corruption layer","n","a translation layer in front of a messy system","لایه ضدفساد","ای‌سی‌ال"],
  ["bounded context","n","a DDD wall around one model of the domain","بافت محدود دامنه","باندد کانتکست"],
  ["ubiquitous language","n","shared words used by code and domain experts","زبان فراگیر دامنه","یوبی‌کویتوس"],
  ["aggregate","n","a cluster of objects treated as one for consistency","تجمع دامنه","اگرگیت"],
  ["entity","n","an object with identity over time","موجودیت","انتیتی"],
  ["value object","n","an object defined only by its fields","شیء مقدار","ولیو آبجکت"],
  ["domain event","n","a fact that happened in the business","رویداد دامنه","دامین ایونت"],
  ["application service","n","orchestration that does not hold business rules","سرویس برنامه","اپ سرویس"],
  ["domain service","n","business logic that does not belong on one entity","سرویس دامنه","دامین سرویس"],
  ["repository","n","an abstraction over storage for a collection","مخزن دامنه","ریپازیتوری"],
  ["unit of work","n","a tracker of changes to flush as one transaction","واحد کار","یونیت آو ورک"],
  ["specification","n","a named business rule you can combine","مشخصه دامنه","اسپسیفیکیشن"],
  ["factory","n","code whose job is creating complex objects","کارخانه ساخت شیء","فکتوری"],
  ["builder","n","an API that constructs an object step by step","بیلدر","بیلدر"],
  ["strategy","n","swappable algorithms behind one interface","استراتژی","استراتژی"],
  ["observer pattern","n","notifying dependents of state changes","الگوی ناظر","آبزرور"],
  ["mediator","n","an object that keeps colleagues from talking directly","میانجی","مدیتور"],
  ["facade","n","a simple front for a noisy subsystem","نما","فساد"],
  ["proxy pattern","n","a stand-in that controls access to another object","الگوی پروکسی","پروکسی پترن"],
  ["decorator pattern","n","stacking behavior by wrapping","الگوی دکوراتور","دکوراتور پترن"],
  ["command pattern","n","an object that represents a request","الگوی فرمان","کامند پترن"],
  ["chain of responsibility","n","handlers that may pass a request along","زنجیره مسئولیت","چین آو رسپ"],
  ["visitor","n","an operation over a structure without changing the types","بازدیدکننده","ویزیتور"],
  ["flyweight","n","sharing fine-grained objects to save memory","وزن‌مگس","فلای‌ویت"],
  ["bridge pattern","n","splitting abstraction from implementation","الگوی پل","بریج"],
  ["composite","n","a tree where leaves and nodes share an API","ترکیبی","کامپوزیت"],
  ["template method","n","an algorithm with overridable steps","روش قالب","تمپلیت متد"],
  ["state pattern","n","an object that changes behavior as its state changes","الگوی حالت","استیت پترن"],
  ["memento","n","a snapshot that can restore an object","یادگار حالت","مmento"],
  ["interpreter pattern","n","a grammar represented as objects","الگوی مفسر","اینترپرتر پترن"],
  ["null object","n","a do-nothing stand-in instead of null checks","شیء تهی","نال آبجکت"],
  ["dependency inversion","n","depending on abstractions, not concretions","وارونگی وابستگی","دی‌آی"],
  ["open-closed","n","open to extension, closed to modification","باز-بسته","اوپن‌کلوزد"],
  ["Liskov","n","subtypes must honor parent contracts","اصل لیسکوف","لیسکوف"],
  ["interface segregation","n","small focused interfaces beat fat ones","جداسازی رابط","آی‌اس‌پی"],
  ["single responsibility","n","one reason to change","مسئولیت واحد","اس‌آر‌پی"],
  ["12-factor","n","a set of rules for cloud-native apps","دوازده‌عاملی","دوازده فاکتور"],
  ["stateless","adj","keeping no local session between requests","بدون حالت محلی","استیت‌لس"],
  ["disposable","adj","safe to throw away and replace","قابل دور ریختن","دیسپوزبل"],
  ["config in env","n","putting settings in the environment, not the image","پیکربندی در محیط","کانفیگ این انو"],
  ["dev/prod parity","n","keeping environments as similar as you can","شباهت توسعه و تولید","پَریتی"],
  ["admin process","n","one-off tasks run as the same app","فرایند ادمین","ادمین پروسس"],
  ["port binding","n","exporting a service by binding a port","اتصال به پورت","پورت بایندینگ"],
  ["concurrency via process","n","scaling out by running more processes","همزمانی با فرایند بیشتر","کانکارنسی"],
  ["logs as streams","n","writing logs to stdout as events","لاگ به‌صورت جریان","لاگ استریم"],
  ["backing service","n","a database or queue treated as an attached resource","سرویس پشتیبان","بکینگ سرویس"],
];
