/** Remaining daily-use tuples to reach 1024 unique words. */
export const dailyRest = [
  ["cabin","n","a small wooden house","کلبه","کلبه"],
  ["cable","n","a thick wire","کابل","کابل"],
  ["cafe","n","a small restaurant","کافه","کافه"],
  ["cake","n","a sweet baked food","کیک","کیک"],
  ["calculate","v","to work out a number","محاسبه کردن","محاسبه کنید"],
  ["call","v","to telephone; to name","تماس گرفتن","تماس بگیرید"],
  ["calm","adj","not excited or angry","آرام","آرام"],
  ["camera","n","a device that takes pictures","دوربین","دوربین"],
  ["camp","n","a place with tents","اردوگاه","اردوگاه"],
  ["campaign","n","a planned set of actions","کارزار","کارزار"],
  ["can","v","to be able to","توانستن","بتوانید"],
  ["cancel","v","to stop a plan","لغو کردن","لغو کنید"],
  ["cancer","n","a serious disease of cells","سرطان","سرطان"],
  ["candidate","n","a person seeking a job or office","نامزد","نامزد"],
  ["candle","n","wax with a wick that burns","شمع","شمع"],
  ["candy","n","a sweet food","آب‌نبات","آب‌نبات"],
  ["cap","n","a soft hat","کلاه","کلاه"],
  ["capable","adj","able to do something","قادر","قادر"],
  ["capacity","n","the amount something can hold","ظرفیت","ظرفیت"],
  ["capital","n","the main city of a country; money for business","پایتخت؛ سرمایه","پایتخت"],
  ["captain","n","the leader of a team or ship","کاپیتان","کاپیتان"],
  ["capture","v","to catch","گرفتن","بگیرید"],
  ["car","n","a road vehicle with four wheels","خودرو","خودرو"],
  ["carbon","n","a chemical element in living things","کربن","کربن"],
  ["card","n","a small piece of stiff paper","کارت","کارت"],
  ["care","n","attention and protection","مراقبت","مراقبت"],
  ["career","n","a job you do for a long time","شغل حرفه‌ای","شغل"],
  ["careful","adj","taking care to avoid harm","محتاط","محتاط"],
  ["careless","adj","not careful","بی‌دقت","بی‌دقت"],
  ["carpet","n","a thick covering for a floor","فرش","فرش"],
  ["carry","v","to take from one place to another","حمل کردن","حمل کنید"],
  ["case","n","a situation; a container","مورد؛ جعبه","مورد"],
  ["cash","n","money in coins and notes","پول نقد","پول نقد"],
  ["cast","v","to throw; to choose actors","انداختن؛ انتخاب بازیگر","انتخاب کنید"],
  ["castle","n","a large strong building","قلعه","قلعه"],
  ["cat","n","a small furry pet","گربه","گربه"],
  ["catch","v","to stop and hold something moving","گرفتن","بگیرید"],
  ["category","n","a group of similar things","دسته","دسته"],
  ["cause","n","the reason something happens","علت","علت"],
  ["cease","v","to stop","متوقف شدن","متوقف شوید"],
  ["ceiling","n","the top inside surface of a room","سقف","سقف"],
  ["celebrate","v","to mark a happy event","جشن گرفتن","جشن بگیرید"],
  ["celebration","n","a happy event or party","جشن","جشن"],
  ["cell","n","the smallest unit of a living thing; a small room","سلول؛ سلول زندان","سلول"],
  ["center","n","the middle point","مرکز","مرکز"],
  ["central","adj","in the middle; most important","مرکزی","مرکزی"],
  ["century","n","one hundred years","قرن","قرن"],
  ["ceremony","n","a formal event","مراسم","مراسم"],
  ["certain","adj","sure","مطمئن","مطمئن"],
  ["certainly","adv","without doubt","حتماً","حتماً"],
  ["chain","n","connected metal rings","زنجیر","زنجیر"],
  ["chair","n","a seat for one person","صندلی","صندلی"],
  ["chairman","n","the leader of a meeting","رئیس جلسه","رئیس"],
  ["challenge","n","a difficult task","چالش","چالش"],
  ["champion","n","the winner of a competition","قهرمان","قهرمان"],
  ["chance","n","a possibility","شانس؛ فرصت","فرصت"],
  ["change","v","to make different","عوض کردن","عوض کنید"],
  ["channel","n","a television station; a waterway","شبکه؛ کانال","کانال"],
  ["chapter","n","a section of a book","فصل","فصل"],
  ["character","n","a person in a story; personality","شخصیت","شخصیت"],
  ["charge","v","to ask for payment; to accuse","هزینه گرفتن؛ متهم کردن","هزینه بگیرید"],
  ["charity","n","an organization that helps people","خیریه","خیریه"],
  ["charm","n","the quality of being attractive","جذابیت","جذابیت"],
  ["chart","n","a drawing of information","نمودار","نمودار"],
  ["chase","v","to run after","تعقیب کردن","تعقیب کنید"],
  ["cheap","adj","low in price","ارزان","ارزان"],
  ["cheat","v","to act dishonestly","تقلب کردن","تقلب کنید"],
  ["check","v","to look at something to make sure","بررسی کردن","بررسی کنید"],
  ["cheek","n","the side of the face","گونه","گونه"],
  ["cheer","v","to shout in support","هورا کشیدن","هورا بکشید"],
  ["cheese","n","a food made from milk","پنیر","پنیر"],
  ["chef","n","a professional cook","سرآشپز","سرآشپز"],
  ["chemical","n","a substance used in chemistry","مادهٔ شیمیایی","مادهٔ شیمیایی"],
  ["chemistry","n","the science of substances","شیمی","شیمی"],
  ["chest","n","the front of the body between neck and stomach","سینه","سینه"],
  ["chew","v","to crush food with the teeth","جویدن","بجوید"],
  ["chicken","n","a bird kept for eggs and meat","مرغ","مرغ"],
  ["chief","n","the leader","رئیس","رئیس"],
  ["child","n","a young person","کودک","کودک"],
  ["childhood","n","the time of being a child","کودکی","کودکی"],
  ["chip","n","a thin piece; a fried potato","تراشه؛ چیپس","چیپس"],
  ["chocolate","n","a sweet brown food","شکلات","شکلات"],
  ["choice","n","an act of choosing","انتخاب","انتخاب"],
  ["choose","v","to pick from options","انتخاب کردن","انتخاب کنید"],
  ["church","n","a building for Christian worship","کلیسا","کلیسا"],
  ["cigarette","n","tobacco rolled in paper for smoking","سیگار","سیگار"],
  ["cinema","n","a place to watch films","سینما","سینما"],
  ["circle","n","a round shape","دایره","دایره"],
  ["circuit","n","a closed path for electricity","مدار","مدار"],
  ["circumstance","n","a fact that affects a situation","شرایط","شرایط"],
  ["cite","v","to mention as proof","استناد کردن","استناد کنید"],
  ["citizen","n","a legal member of a country","شهروند","شهروند"],
  ["city","n","a large town","شهر","شهر"],
  ["civil","adj","relating to citizens, not military","مدنی","مدنی"],
  ["claim","v","to say something is true","ادعا کردن","ادعا کنید"],
  ["clap","v","to hit the hands together","کف زدن","کف بزنید"],
  ["clarify","v","to make clearer","روشن کردن","روشن کنید"],
  ["class","n","a group of students; a category","کلاس؛ طبقه","کلاس"],
  ["classic","adj","of lasting high quality","کلاسیک","کلاسیک"],
  ["classroom","n","a room for teaching","کلاس درس","کلاس درس"],
  ["clause","n","a part of a sentence or contract","بند","بند"],
  ["clean","adj","not dirty","تمیز","تمیز"],
  ["clear","adj","easy to understand; not blocked","واضح؛ باز","واضح"],
  ["clerk","n","an office worker","منشی","منشی"],
  ["clever","adj","quick to learn","باهوش","باهوش"],
  ["click","v","to press a mouse button","کلیک کردن","کلیک کنید"],
  ["client","n","a customer","مشتری","مشتری"],
  ["climate","n","the usual weather","اقلیم","اقلیم"],
  ["climb","v","to go up","بالا رفتن","بالا بروید"],
  ["clock","n","a device that shows time","ساعت","ساعت"],
  ["close","v","to shut","بستن","ببندید"],
  ["cloth","n","material for making clothes","پارچه","پارچه"],
  ["clothes","n","things you wear","لباس","لباس"],
  ["cloud","n","a mass of water drops in the sky","ابر","ابر"],
  ["club","n","a group of people with a shared interest","باشگاه","باشگاه"],
  ["clue","n","a piece of information that helps solve something","سرنخ","سرنخ"],
  ["coach","n","a trainer","مربی","مربی"],
  ["coal","n","a black rock burned for heat","زغال‌سنگ","زغال‌سنگ"],
  ["coast","n","land next to the sea","ساحل","ساحل"],
  ["coat","n","an outer piece of clothing","کت","کت"],
  ["code","n","a system of signs or rules","رمز؛ کد","کد"],
  ["coffee","n","a hot drink from roasted beans","قهوه","قهوه"],
  ["coin","n","a metal piece of money","سکه","سکه"],
  ["cold","adj","low in temperature","سرد","سرد"],
  ["collapse","v","to fall down","فروریختن","فرو بریزد"],
  ["colleague","n","a person you work with","همکار","همکار"],
  ["collect","v","to bring together","جمع کردن","جمع کنید"],
  ["collection","n","a group of things gathered","مجموعه","مجموعه"],
  ["college","n","a place of higher education","دانشکده","دانشکده"],
  ["color","n","red, blue, green, and so on","رنگ","رنگ"],
  ["column","n","a tall post; a vertical list","ستون","ستون"],
  ["combination","n","things joined together","ترکیب","ترکیب"],
  ["combine","v","to join together","ترکیب کردن","ترکیب کنید"],
  ["come","v","to move toward the speaker","آمدن","بیایید"],
  ["comfort","n","a feeling of ease","آسایش","آسایش"],
  ["comfortable","adj","giving ease","راحت","راحت"],
  ["command","n","an order","فرمان","فرمان"],
  ["comment","n","a spoken or written remark","نظر","نظر"],
  ["commerce","n","the buying and selling of goods","تجارت","تجارت"],
  ["commercial","adj","related to business","تجاری","تجاری"],
  ["commission","n","a fee; a group given a task","حق‌العمل؛ کمیسیون","کمیسیون"],
  ["commit","v","to promise; to do a crime","متعهد شدن؛ مرتکب شدن","متعهد شوید"],
  ["commitment","n","a promise to do something","تعهد","تعهد"],
  ["committee","n","a small group that makes decisions","کمیته","کمیته"],
  ["common","adj","happening often; shared","رایج؛ مشترک","رایج"],
  ["communicate","v","to share information","ارتباط برقرار کردن","ارتباط برقرار کنید"],
  ["communication","n","the act of sharing information","ارتباط","ارتباط"],
  ["community","n","people living in one area","جامعه","جامعه"],
  ["company","n","a business","شرکت","شرکت"],
  ["compare","v","to look at similarities and differences","مقایسه کردن","مقایسه کنید"],
  ["comparison","n","the act of comparing","مقایسه","مقایسه"],
  ["compete","v","to try to win","رقابت کردن","رقابت کنید"],
  ["competition","n","an event where people try to win","رقابت","رقابت"],
  ["competitor","n","someone you compete with","رقیب","رقیب"],
  ["complain","v","to say you are unhappy","شکایت کردن","شکایت کنید"],
  ["complaint","n","a statement of unhappiness","شکایت","شکایت"],
  ["complete","adj","finished; whole","کامل","کامل"],
  ["complex","adj","having many parts","پیچیده","پیچیده"],
  ["complicate","v","to make more difficult","پیچیده کردن","پیچیده کنید"],
  ["component","n","one part of a whole","جزء","جزء"],
  ["compose","v","to create music or text","ساختن؛ تصنیف کردن","بسازید"],
  ["composition","n","a piece of writing or music","قطعه؛ ترکیب","ترکیب"],
  ["compound","n","something made of two or more parts","ترکیب","ترکیب"],
  ["comprehensive","adj","including everything","جامع","جامع"],
  ["comprise","v","to be made up of","شامل بودن","شامل باشد"],
  ["computer","n","an electronic machine that processes data","رایانه","رایانه"],
  ["concentrate","v","to give all your attention","تمرکز کردن","تمرکز کنید"],
  ["concept","n","an idea","مفهوم","مفهوم"],
  ["concern","n","a worry","نگرانی","نگرانی"],
  ["concert","n","a musical performance","کنسرت","کنسرت"],
  ["conclude","v","to finish; to decide after thinking","نتیجه‌گیری کردن","نتیجه بگیرید"],
  ["conclusion","n","the end; a decision","نتیجه","نتیجه"],
  ["concrete","n","a hard building material","بتن","بتن"],
  ["condition","n","the state of something","وضعیت","وضعیت"],
  ["conduct","v","to organize and carry out","انجام دادن","انجام دهید"],
  ["conference","n","a formal meeting","کنفرانس","کنفرانس"],
  ["confidence","n","belief in yourself","اعتمادبه‌نفس","اعتمادبه‌نفس"],
  ["confident","adj","sure of yourself","مطمئن به خود","مطمئن"],
  ["confirm","v","to say that something is true","تأیید کردن","تأیید کنید"],
  ["conflict","n","a serious disagreement","درگیری","درگیری"],
  ["confuse","v","to make unclear","گیج کردن","گیج کنید"],
  ["connect","v","to join","وصل کردن","وصل کنید"],
  ["connection","n","a link","ارتباط","ارتباط"],
  ["conscious","adj","awake and aware","هوشیار","هوشیار"],
  ["consequence","n","a result","پیامد","پیامد"],
  ["conservative","adj","preferring traditional ideas","محافظه‌کار","محافظه‌کار"],
  ["consider","v","to think about","در نظر گرفتن","در نظر بگیرید"],
  ["considerable","adj","large in size or amount","قابل‌توجه","قابل‌توجه"],
  ["consist","v","to be made of","متشکل بودن از","متشکل باشد"],
  ["consistent","adj","always the same in quality","پایدار؛ یکدست","یکدست"],
  ["constant","adj","happening all the time","دائمی","دائمی"],
  ["construct","v","to build","ساختن","بسازید"],
  ["construction","n","the work of building","ساخت‌وساز","ساخت‌وساز"],
  ["consult","v","to ask for advice","مشورت کردن","مشورت کنید"],
  ["consume","v","to use up","مصرف کردن","مصرف کنید"],
  ["consumer","n","a person who buys goods","مصرف‌کننده","مصرف‌کننده"],
  ["contact","n","communication","تماس","تماس"],
  ["contain","v","to have inside","شامل بودن","شامل باشد"],
  ["container","n","an object that holds things","ظرف","ظرف"],
  ["contemporary","adj","modern; of the same time","معاصر","معاصر"],
  ["content","n","the things inside","محتوا","محتوا"],
  ["contest","n","a competition","مسابقه","مسابقه"],
  ["context","n","the situation around something","بافت؛ زمینه","زمینه"],
  ["continent","n","a large land mass","قاره","قاره"],
  ["continue","v","to keep doing","ادامه دادن","ادامه دهید"],
  ["continuous","adj","without a break","پیوسته","پیوسته"],
  ["contract","n","a legal agreement","قرارداد","قرارداد"],
  ["contrast","n","a clear difference","تفاوت آشکار","تفاوت"],
  ["contribute","v","to give in order to help","مشارکت کردن","مشارکت کنید"],
  ["contribution","n","something given to help","مشارکت","مشارکت"],
  ["control","v","to have power over","کنترل کردن","کنترل کنید"],
  ["convenient","adj","easy to use or reach","راحت؛ مناسب","مناسب"],
  ["convention","n","a large meeting; a usual way","همایش؛ عرف","عرف"],
  ["conversation","n","a spoken exchange","گفتگو","گفتگو"],
  ["convert","v","to change into another form","تبدیل کردن","تبدیل کنید"],
  ["convince","v","to make someone believe","متقاعد کردن","متقاعد کنید"],
  ["cook","v","to prepare food with heat","پختن","بپزید"],
  ["cool","adj","fairly cold; stylish","خنک؛ شیک","خنک"],
  ["cooperate","v","to work together","همکاری کردن","همکاری کنید"],
  ["cope","v","to deal successfully with","کنار آمدن","کنار بیایید"],
  ["copy","n","one of several identical things","نسخه","نسخه"],
  ["core","n","the central part","هسته","هسته"],
  ["corn","n","a yellow grain","ذرت","ذرت"],
  ["corner","n","the place where two sides meet","گوشه","گوشه"],
  ["corporate","adj","relating to a large company","شرکتی","شرکتی"],
  ["correct","adj","true; without mistakes","درست","درست"],
  ["cost","n","the amount you pay","هزینه","هزینه"],
  ["cottage","n","a small house in the country","کلبه روستایی","کلبه"],
  ["cotton","n","a plant fiber used for cloth","پنبه","پنبه"],
  ["could","v","past of can; possibility","می‌توانست؛ شاید","بتواند"],
  ["council","n","a group that governs locally","شورا","شورا"],
  ["count","v","to say numbers in order","شمردن","بشمارید"],
  ["counter","n","a long table in a shop","پیشخوان","پیشخوان"],
  ["country","n","a nation; land outside cities","کشور؛ روستا","کشور"],
  ["countryside","n","land away from towns","حومه و روستا","روستا"],
  ["county","n","a region of a country","شهرستان","شهرستان"],
  ["couple","n","two people; a few","زوج؛ چند","زوج"],
  ["courage","n","the ability to face fear","شجاعت","شجاعت"],
  ["course","n","a series of lessons; a direction","دوره؛ مسیر","دوره"],
  ["court","n","a place where legal cases are heard","دادگاه","دادگاه"],
  ["cousin","n","the child of an aunt or uncle","پسرخاله یا دخترعمو","پسرعمو"],
  ["cover","v","to put something over","پوشاندن","بپوشانید"],
  ["cow","n","a large farm animal that gives milk","گاو","گاو"],
  ["crack","n","a thin line where something is broken","ترک","ترک"],
  ["craft","n","a skill of making things by hand","صنعت دستی","صنعت دستی"],
  ["crash","v","to hit something hard","تصادف کردن","تصادف کنید"],
  ["crazy","adj","very strange or unwise","دیوانه‌وار","عجیب"],
  ["cream","n","the thick part of milk","خامه","خامه"],
  ["create","v","to make something new","خلق کردن","خلق کنید"],
  ["creation","n","something that has been made","آفرینش","آفرینش"],
  ["creative","adj","good at making new ideas","خلاق","خلاق"],
  ["creature","n","a living being","موجود","موجود"],
  ["credit","n","praise; money you can borrow","اعتبار","اعتبار"],
  ["crew","n","the people who work on a ship or plane","خدمه","خدمه"],
  ["crime","n","an illegal act","جرم","جرم"],
  ["criminal","n","a person who commits crime","مجرم","مجرم"],
  ["crisis","n","a time of great difficulty","بحران","بحران"],
  ["criterion","n","a standard for judging","معیار","معیار"],
  ["critic","n","a person who judges art or ideas","منتقد","منتقد"],
  ["critical","adj","very important; finding faults","حیاتی؛ انتقادی","حیاتی"],
  ["criticism","n","remarks about faults","انتقاد","انتقاد"],
  ["criticize","v","to say what is wrong","انتقاد کردن","انتقاد کنید"],
  ["crop","n","plants grown for food","محصول کشاورزی","محصول"],
  ["cross","v","to go from one side to the other","عبور کردن","عبور کنید"],
  ["crowd","n","a large group of people","جمعیت","جمعیت"],
  ["crown","n","a royal head covering","تاج","تاج"],
  ["crucial","adj","extremely important","حیاتی","حیاتی"],
  ["cruel","adj","causing pain without care","بی‌رحم","بی‌رحم"],
  ["cry","v","to produce tears","گریه کردن","گریه کنید"],
  ["cultural","adj","relating to culture","فرهنگی","فرهنگی"],
  ["culture","n","the customs and arts of a people","فرهنگ","فرهنگ"],
  ["cup","n","a small container for drinks","فنجان","فنجان"],
  ["cupboard","n","a piece of furniture with shelves","کمد","کمد"],
  ["cure","n","a treatment that ends an illness","درمان","درمان"],
  ["curious","adj","wanting to know","کنجکاو","کنجکاو"],
  ["current","adj","happening now","فعلی","فعلی"],
  ["curriculum","n","the subjects taught","برنامهٔ درسی","برنامهٔ درسی"],
  ["curtain","n","cloth covering a window","پرده","پرده"],
  ["curve","n","a bent line","خمیدگی","خمیدگی"],
  ["custom","n","a usual way of behaving","رسم","رسم"],
  ["customer","n","a person who buys","مشتری","مشتری"],
  ["cut","v","to divide with a sharp tool","بریدن","ببرید"],
  ["cycle","n","a series that repeats","چرخه","چرخه"],
  ["dad","n","father","پدر","پدر"],
  ["daily","adj","happening every day","روزانه","روزانه"],
  ["damage","n","harm","آسیب","آسیب"],
  ["dance","v","to move to music","رقصیدن","برقصید"],
  ["danger","n","the chance of harm","خطر","خطر"],
  ["dangerous","adj","likely to cause harm","خطرناک","خطرناک"],
  ["dare","v","to be brave enough","جرئت کردن","جرئت کنید"],
  ["dark","adj","with little light","تاریک","تاریک"],
  ["data","n","facts and figures","داده","داده"],
  ["date","n","a particular day","تاریخ","تاریخ"],
  ["daughter","n","a female child","دختر","دختر"],
  ["dawn","n","the first light of day","سپیده‌دم","سپیده‌دم"],
  ["day","n","a period of twenty-four hours","روز","روز"],
  ["dead","adj","no longer alive","مرده","مرده"],
  ["deal","n","an agreement","معامله","معامله"],
  ["dear","adj","loved; expensive","عزیز؛ گران","عزیز"],
  ["death","n","the end of life","مرگ","مرگ"],
  ["debate","n","a formal discussion","مناظره","مناظره"],
  ["debt","n","money owed","بدهی","بدهی"],
  ["decade","n","ten years","دهه","دهه"],
  ["decent","adj","acceptable and honest","آبرومند","آبرومند"],
  ["decide","v","to choose after thinking","تصمیم گرفتن","تصمیم بگیرید"],
  ["decision","n","a choice made","تصمیم","تصمیم"],
  ["declare","v","to say officially","اعلام کردن","اعلام کنید"],
  ["decline","v","to become less; to refuse","کاهش یافتن؛ رد کردن","کاهش یابد"],
  ["decorate","v","to add things to make more attractive","تزئین کردن","تزئین کنید"],
  ["decrease","v","to become smaller","کاهش یافتن","کاهش یابد"],
  ["deep","adj","going far down","عمیق","عمیق"],
  ["defeat","v","to win against","شکست دادن","شکست دهید"],
  ["defence","n","protection against attack","دفاع","دفاع"],
  ["defend","v","to protect from attack","دفاع کردن","دفاع کنید"],
  ["define","v","to explain the meaning","تعریف کردن","تعریف کنید"],
  ["definite","adj","clear and certain","قطعی","قطعی"],
  ["definition","n","the meaning of a word","تعریف","تعریف"],
  ["degree","n","a unit of temperature; a university award","درجه؛ مدرک","مدرک"],
  ["delay","n","a period of waiting","تأخیر","تأخیر"],
  ["delete","v","to remove","حذف کردن","حذف کنید"],
  ["deliberate","adj","done on purpose","عمدی","عمدی"],
  ["delicate","adj","easily damaged; fine","ظریف","ظریف"],
  ["delight","n","great pleasure","لذت","لذت"],
  ["deliver","v","to take to a person or place","تحویل دادن","تحویل دهید"],
  ["delivery","n","the act of delivering","تحویل","تحویل"],
  ["demand","n","a strong request","تقاضا","تقاضا"],
  ["democracy","n","government by the people","دموکراسی","دموکراسی"],
  ["democratic","adj","based on democracy","دموکراتیک","دموکراتیک"],
  ["demonstrate","v","to show clearly","نشان دادن","نشان دهید"],
  ["dentist","n","a doctor for teeth","دندان‌پزشک","دندان‌پزشک"],
  ["deny","v","to say something is not true","انکار کردن","انکار کنید"],
  ["department","n","a section of an organization","بخش","بخش"],
  ["departure","n","the act of leaving","حرکت؛ عزیمت","عزیمت"],
  ["depend","v","to need someone or something","وابسته بودن","وابسته باشید"],
  ["dependent","adj","needing support","وابسته","وابسته"],
  ["deposit","n","money paid as a first amount","بیعانه","بیعانه"],
  ["depress","v","to make sad","افسرده کردن","افسرده کنید"],
  ["depth","n","how deep something is","عمق","عمق"],
  ["describe","v","to say what something is like","توصیف کردن","توصیف کنید"],
  ["description","n","an account of what something is like","توصیف","توصیف"],
  ["desert","n","a dry sandy region","بیابان","بیابان"],
  ["deserve","v","to have earned something","سزاوار بودن","سزاوار باشید"],
  ["design","n","a plan or drawing","طرح","طرح"],
  ["designer","n","a person who plans how things look","طراح","طراح"],
  ["desire","n","a strong wish","میل","میل"],
  ["desk","n","a table for writing","میز کار","میز کار"],
  ["desperate","adj","ready to do anything because of need","مستأصل","مستأصل"],
  ["despite","prep","even though","علیرغم","علیرغم"],
  ["destroy","v","to damage so badly it cannot be used","نابود کردن","نابود کنید"],
  ["destruction","n","the act of destroying","نابودی","نابودی"],
  ["detail","n","a small fact","جزئیات","جزئیات"],
  ["detect","v","to notice","کشف کردن","کشف کنید"],
  ["determine","v","to decide; to find out","تعیین کردن","تعیین کنید"],
  ["develop","v","to grow or improve","توسعه دادن","توسعه دهید"],
  ["development","n","growth or change","توسعه","توسعه"],
  ["device","n","a tool or machine","دستگاه","دستگاه"],
  ["devote","v","to give time or energy to","اختصاص دادن","اختصاص دهید"],
  ["diagram","n","a simple drawing that explains","نمودار","نمودار"],
  ["dialogue","n","conversation","گفت‌وگو","گفت‌وگو"],
  ["diamond","n","a precious clear stone","الماس","الماس"],
  ["diary","n","a book for writing daily notes","دفتر خاطرات","دفتر خاطرات"],
  ["dictionary","n","a book of word meanings","واژه‌نامه","واژه‌نامه"],
  ["die","v","to stop living","مردن","بمیرید"],
  ["diet","n","the food you usually eat","رژیم غذایی","رژیم"],
  ["differ","v","to be unlike","تفاوت داشتن","تفاوت داشته باشد"],
  ["difference","n","the way things are not the same","تفاوت","تفاوت"],
  ["different","adj","not the same","متفاوت","متفاوت"],
  ["difficult","adj","not easy","سخت","سخت"],
  ["difficulty","n","a problem","دشواری","دشواری"],
  ["dig","v","to make a hole in the ground","کندن","بکنید"],
  ["digital","adj","using computer numbers","دیجیتال","دیجیتال"],
  ["dinner","n","the main meal of the day","شام","شام"],
  ["direct","adj","straight; without stopping","مستقیم","مستقیم"],
  ["direction","n","the way something moves","جهت","جهت"],
  ["director","n","a person who manages","مدیر","مدیر"],
  ["dirt","n","unclean material","کثیفی","کثیفی"],
  ["dirty","adj","not clean","کثیف","کثیف"],
  ["disabled","adj","having a physical or mental condition that limits activity","معلول","معلول"],
  ["disagree","v","to have a different opinion","مخالف بودن","مخالف باشید"],
  ["disappear","v","to become impossible to see","ناپدید شدن","ناپدید شوید"],
  ["disaster","n","a sudden event that causes great harm","فاجعه","فاجعه"],
  ["discipline","n","control of behavior","انضباط","انضباط"],
  ["discount","n","a reduction in price","تخفیف","تخفیف"],
  ["discover","v","to find for the first time","کشف کردن","کشف کنید"],
  ["discovery","n","something found for the first time","کشف","کشف"],
  ["discuss","v","to talk about","بحث کردن درباره","بحث کنید"],
  ["discussion","n","a talk about a subject","بحث","بحث"],
  ["disease","n","an illness","بیماری","بیماری"],
  ["dish","n","a plate of food","ظرف غذا","ظرف"],
  ["disk","n","a flat round object","دیسک","دیسک"],
  ["dislike","v","to not like","دوست نداشتن","دوست نداشته باشید"],
  ["dismiss","v","to send away; to reject","رد کردن؛ اخراج کردن","رد کنید"],
  ["display","v","to show","نمایش دادن","نمایش دهید"],
  ["distance","n","the space between two points","فاصله","فاصله"],
  ["distant","adj","far away","دور","دور"],
  ["distinct","adj","clearly different","متمایز","متمایز"],
  ["distinguish","v","to see a difference","تمایز قائل شدن","تمایز قائل شوید"],
  ["distribute","v","to give out","توزیع کردن","توزیع کنید"],
  ["distribution","n","the way things are shared","توزیع","توزیع"],
  ["district","n","an area of a city or country","منطقه","منطقه"],
  ["disturb","v","to interrupt","مزاحم شدن","مزاحم شوید"],
  ["divide","v","to split into parts","تقسیم کردن","تقسیم کنید"],
  ["division","n","the act of dividing","تقسیم","تقسیم"],
  ["divorce","n","the legal end of a marriage","طلاق","طلاق"],
  ["do","v","to perform an action","انجام دادن","انجام دهید"],
  ["doctor","n","a person trained to treat illness","پزشک","پزشک"],
  ["document","n","a paper with official information","سند","سند"],
  ["dog","n","a common four-legged pet","سگ","سگ"],
  ["dollar","n","a unit of money","دلار","دلار"],
  ["domestic","adj","relating to the home or the country","خانگی؛ داخلی","داخلی"],
  ["dominant","adj","strongest or most important","غالب","غالب"],
  ["dominate","v","to have control over","تسلط داشتن","تسلط داشته باشید"],
  ["donate","v","to give for a good cause","اهدای کردن","اهدا کنید"],
  ["door","n","a movable barrier at an entrance","در","در"],
  ["double","adj","twice as much","دو برابر","دو برابر"],
  ["doubt","n","a feeling of not being sure","تردید","تردید"],
  ["down","adv","to a lower place","پایین","پایین"],
  ["download","v","to copy data onto a computer","دانلود کردن","دانلود کنید"],
  ["downstairs","adv","to a lower floor","طبقه پایین","طبقه پایین"],
  ["downtown","n","the central part of a city","مرکز شهر","مرکز شهر"],
  ["dozen","n","twelve","دوجین","دوجین"],
  ["draft","n","a first version of a text","پیش‌نویس","پیش‌نویس"],
  ["drag","v","to pull along the ground","کشیدن","بکشید"],
  ["drama","n","a play; exciting events","نمایش؛ درام","نمایش"],
  ["dramatic","adj","sudden and exciting","نمایشی؛ چشمگیر","چشمگیر"],
  ["draw","v","to make a picture with a pen","کشیدن نقاشی","نقاشی بکشید"],
  ["drawer","n","a box that slides in furniture","کشو","کشو"],
  ["dream","n","images in sleep; a hope","رویا","رویا"],
  ["dress","n","a piece of clothing for women","پیراهن زنانه","پیراهن"],
  ["drink","v","to take liquid into the mouth","نوشیدن","بنوشید"],
  ["drive","v","to control a vehicle","رانندگی کردن","رانندگی کنید"],
  ["driver","n","a person who drives","راننده","راننده"],
  ["drop","v","to let fall","انداختن","بیندازید"],
  ["drug","n","a medicine; an illegal substance","دارو؛ مادهٔ مخدر","دارو"],
  ["drum","n","a musical instrument you hit","طبل","طبل"],
  ["dry","adj","without water","خشک","خشک"],
  ["due","adj","expected; owed","موعد؛ بدهکار","موعد"],
  ["during","prep","throughout a period of","در طول","در طول"],
  ["dust","n","fine dry dirt","گرد و غبار","گرد و غبار"],
  ["duty","n","something you must do","وظیفه","وظیفه"],
  ["each","det","every one separately","هر یک","هر یک"],
  ["ear","n","the organ of hearing","گوش","گوش"],
  ["early","adj","near the beginning","زود","زود"],
  ["earn","v","to get money by working","درآمد کسب کردن","کسب کنید"],
  ["earth","n","the planet we live on; soil","زمین","زمین"],
  ["ease","n","lack of difficulty","سهولت","سهولت"],
  ["east","n","the direction of sunrise","شرق","شرق"],
  ["eastern","adj","in the east","شرقی","شرقی"],
  ["easy","adj","not difficult","آسان","آسان"],
  ["eat","v","to take food into the body","خوردن","بخورید"],
  ["economic","adj","relating to trade and money","اقتصادی","اقتصادی"],
  ["economy","n","the system of money and jobs","اقتصاد","اقتصاد"],
  ["edge","n","the outside limit","لبه","لبه"],
  ["edition","n","a particular version of a book","نسخه","نسخه"],
  ["editor","n","a person who prepares text","ویراستار","ویراستار"],
  ["educate","v","to teach","آموزش دادن","آموزش دهید"],
  ["education","n","teaching and learning","آموزش","آموزش"],
  ["effect","n","a change caused by something","اثر","اثر"],
  ["effective","adj","producing the result you want","مؤثر","مؤثر"],
  ["efficiency","n","the quality of working well","کارایی","کارایی"],
  ["efficient","adj","working well without waste","کارآمد","کارآمد"],
  ["effort","n","the use of energy to do something","تلاش","تلاش"],
  ["egg","n","an oval object laid by a bird","تخم‌مرغ","تخم‌مرغ"],
  ["either","det","one or the other","هر یک از دو","هر یک"],
  ["elect","v","to choose by voting","انتخاب کردن با رأی","رأی دهید"],
  ["election","n","an event when people vote","انتخابات","انتخابات"],
  ["electric","adj","using electricity","برقی","برقی"],
  ["electricity","n","energy used for light and machines","برق","برق"],
  ["electronic","adj","using small electrical parts","الکترونیکی","الکترونیکی"],
  ["element","n","a basic part","عنصر","عنصر"],
  ["elephant","n","a very large animal with a trunk","فیل","فیل"],
  ["eliminate","v","to remove completely","حذف کردن","حذف کنید"],
  ["else","adv","in addition; different","دیگر","دیگر"],
  ["elsewhere","adv","in another place","جای دیگر","جای دیگر"],
  ["email","n","a message sent by computer","رایانامه","رایانامه"],
  ["embark","v","to start a journey or project","آغاز کردن","آغاز کنید"],
  ["embarrassed","adj","feeling awkward","خجالت‌زده","خجالت‌زده"],
  ["emerge","v","to come out","ظاهر شدن","ظاهر شوید"],
  ["emergency","n","a sudden dangerous situation","اضطراری","اضطراری"],
  ["emotion","n","a strong feeling","هیجان؛ احساس","احساس"],
  ["emotional","adj","connected with feelings","احساسی","احساسی"],
  ["emphasis","n","special importance","تأکید","تأکید"],
  ["emphasize","v","to give special importance","تأکید کردن","تأکید کنید"],
  ["empire","n","a group of countries under one ruler","امپراتوری","امپراتوری"],
  ["employ","v","to give someone a job","استخدام کردن","استخدام کنید"],
  ["employee","n","a person who works for a company","کارمند","کارمند"],
  ["employer","n","a person or company that pays workers","کارفرما","کارفرما"],
  ["employment","n","paid work","اشتغال","اشتغال"],
  ["empty","adj","containing nothing","خالی","خالی"],
  ["enable","v","to make possible","ممکن ساختن","ممکن سازید"],
  ["encounter","v","to meet unexpectedly","مواجه شدن","مواجه شوید"],
  ["encourage","v","to give support and hope","تشویق کردن","تشویق کنید"],
  ["end","n","the last part","پایان","پایان"],
  ["enemy","n","a person who hates you","دشمن","دشمن"],
  ["energy","n","the power to work","انرژی","انرژی"],
  ["engage","v","to take part; to attract","درگیر شدن","درگیر شوید"],
  ["engine","n","a machine that produces power","موتور","موتور"],
  ["engineer","n","a person who designs machines","مهندس","مهندس"],
  ["enhance","v","to improve","بهبود بخشیدن","بهبود بخشید"],
  ["enjoy","v","to take pleasure in","لذت بردن","لذت ببرید"],
  ["enormous","adj","very large","عظیم","عظیم"],
  ["enough","det","as much as needed","کافی","کافی"],
  ["enquiry","n","a question; an official investigation","پرسش؛ تحقیق","پرسش"],
  ["ensure","v","to make sure","اطمینان حاصل کردن","اطمینان حاصل کنید"],
  ["enter","v","to go in","وارد شدن","وارد شوید"],
  ["enterprise","n","a business project","بنگاه","بنگاه"],
  ["entertainment","n","shows and activities that amuse","سرگرمی","سرگرمی"],
  ["enthusiasm","n","eager interest","اشتیاق","اشتیاق"],
  ["entire","adj","whole","تمام","تمام"],
  ["entitle","v","to give a right","حق دادن","حق بدهید"],
  ["entrance","n","a way in","ورودی","ورودی"],
  ["entry","n","the act of going in; an item in a list","ورود؛ مدخل","ورود"],
  ["envelope","n","a paper cover for a letter","پاکت","پاکت"],
  ["environment","n","the natural world around us","محیط‌زیست","محیط‌زیست"],
  ["episode","n","one part of a series","قسمت","قسمت"],
  ["equal","adj","the same in amount or value","برابر","برابر"],
  ["equipment","n","tools needed for a job","تجهیزات","تجهیزات"],
  ["equivalent","adj","equal in value","معادل","معادل"],
  ["era","n","a long period of history","دوران","دوران"],
  ["error","n","a mistake","خطا","خطا"],
  ["escape","v","to get away","فرار کردن","فرار کنید"],
  ["especially","adv","more than usual","به‌ویژه","به‌ویژه"],
  ["essay","n","a short piece of writing","جستار","جستار"],
  ["essential","adj","completely necessary","ضروری","ضروری"],
  ["establish","v","to start something lasting","تأسیس کردن","تأسیس کنید"],
  ["estate","n","land and buildings","املاک","املاک"],
  ["estimate","v","to guess an amount","تخمین زدن","تخمین بزنید"],
  ["ethical","adj","morally right","اخلاقی","اخلاقی"],
  ["ethnic","adj","relating to a cultural group","قومی","قومی"],
  ["euro","n","the currency of many European countries","یورو","یورو"],
  ["evaluate","v","to judge the value of","ارزیابی کردن","ارزیابی کنید"],
  ["even","adv","used to add emphasis","حتی","حتی"],
  ["evening","n","the later part of the day","عصر","عصر"],
  ["event","n","something that happens","رویداد","رویداد"],
  ["eventually","adv","in the end","سرانجام","سرانجام"],
  ["ever","adv","at any time","هرگز؛ همیشه","هرگز"],
  ["every","det","each one","هر","هر"],
  ["everybody","n","every person","همه","همه"],
  ["everyday","adj","used or happening daily","روزمره","روزمره"],
  ["everyone","n","every person","همه کس","همه"],
  ["everything","n","all things","همه‌چیز","همه‌چیز"],
  ["everywhere","adv","in all places","همه‌جا","همه‌جا"],
  ["evidence","n","facts that prove something","شواهد","شواهد"],
  ["evil","adj","very bad and cruel","شرور","شرور"],
  ["exact","adj","completely correct","دقیق","دقیق"],
  ["exactly","adv","in every detail","دقیقاً","دقیقاً"],
  ["exam","n","a formal test","امتحان","امتحان"],
  ["examine","v","to look at carefully","بررسی کردن","بررسی کنید"],
  ["example","n","something that shows a rule","مثال","مثال"],
  ["exceed","v","to go beyond","فراتر رفتن از","فراتر بروید"],
  ["excellent","adj","extremely good","عالی","عالی"],
  ["except","prep","not including","به‌جز","به‌جز"],
  ["exception","n","something that does not follow the rule","استثنا","استثنا"],
  ["exchange","v","to give one thing and get another","مبادله کردن","مبادله کنید"],
  ["excited","adj","very happy and eager","هیجان‌زده","هیجان‌زده"],
  ["excitement","n","a feeling of eager happiness","هیجان","هیجان"],
  ["exciting","adj","causing excitement","هیجان‌انگیز","هیجان‌انگیز"],
  ["exclude","v","to leave out","کنار گذاشتن","کنار بگذارید"],
  ["excuse","n","a reason given for a fault","بهانه","بهانه"],
  ["executive","n","a senior manager","مدیر اجرایی","مدیر"],
  ["exercise","n","physical activity to stay healthy","ورزش","ورزش"],
  ["exhibit","v","to show publicly","به نمایش گذاشتن","به نمایش بگذارید"],
  ["exhibition","n","a public display of art or objects","نمایشگاه","نمایشگاه"],
  ["exist","v","to be real","وجود داشتن","وجود داشته باشد"],
  ["existence","n","the state of being real","وجود","وجود"],
  ["exit","n","a way out","خروجی","خروجی"],
  ["expand","v","to become larger","گسترش یافتن","گسترش یابد"],
  ["expansion","n","the act of growing larger","گسترش","گسترش"],
  ["expect","v","to think something will happen","انتظار داشتن","انتظار داشته باشید"],
  ["expectation","n","a belief that something will happen","انتظار","انتظار"],
  ["expected","adj","thought likely to happen","مورد انتظار","مورد انتظار"],
  ["expedition","n","a journey for a purpose","سفر اکتشافی","سفر"],
  ["expense","n","the money spent","هزینه","هزینه"],
  ["expensive","adj","costing a lot","گران","گران"],
  ["experience","n","knowledge from doing something","تجربه","تجربه"],
  ["experiment","n","a scientific test","آزمایش","آزمایش"],
  ["expert","n","a person with special skill","متخصص","متخصص"],
  ["explain","v","to make clear","توضیح دادن","توضیح دهید"],
  ["explanation","n","the reason given for something","توضیح","توضیح"],
  ["explode","v","to burst with force","منفجر شدن","منفجر شود"],
  ["explore","v","to travel in order to learn","کاوش کردن","کاوش کنید"],
  ["explosion","n","a sudden burst","انفجار","انفجار"],
  ["export","v","to send goods to another country","صادرات کردن","صادر کنید"],
  ["expose","v","to uncover","آشکار کردن","آشکار کنید"],
  ["express","v","to show a feeling or idea","بیان کردن","بیان کنید"],
  ["expression","n","a look on the face; a phrase","بیان؛ عبارت","عبارت"],
  ["extend","v","to make longer","گسترش دادن","گسترش دهید"],
  ["extension","n","an added part","تمدید؛ افزونه","تمدید"],
  ["extensive","adj","covering a large area","گسترده","گسترده"],
  ["extent","n","the size or importance","میزان","میزان"],
  ["external","adj","outside","خارجی","خارجی"],
  ["extra","adj","more than usual","اضافی","اضافی"],
  ["extraordinary","adj","very unusual","فوق‌العاده","فوق‌العاده"],
  ["extreme","adj","very great","شدید","شدید"],
  ["eye","n","the organ of sight","چشم","چشم"],
  ["face","n","the front of the head","صورت","صورت"],
  ["facility","n","a building or service","امکانات","امکانات"],
  ["fact","n","something that is true","واقعیت","واقعیت"],
  ["factor","n","something that affects a result","عامل","عامل"],
  ["factory","n","a building where goods are made","کارخانه","کارخانه"],
  ["fail","v","to not succeed","شکست خوردن","شکست بخورید"],
  ["failure","n","lack of success","شکست","شکست"],
  ["fair","adj","just; reasonably good","منصفانه","منصفانه"],
  ["fairly","adv","to some degree; justly","نسبتاً","نسبتاً"],
  ["faith","n","strong belief","ایمان","ایمان"],
  ["fall","v","to drop down","افتادن","بیفتید"],
  ["false","adj","not true","غلط","غلط"],
  ["familiar","adj","well known","آشنا","آشنا"],
  ["family","n","parents and children","خانواده","خانواده"],
  ["famous","adj","known by many people","مشهور","مشهور"],
  ["fan","n","a person who likes a team or artist","هوادار","هوادار"],
  ["fancy","v","to want; to imagine","خواست؛ تصور کردن","تصور کنید"],
  ["far","adv","a long distance","دور","دور"],
  ["farm","n","land used to grow food","مزرعه","مزرعه"],
  ["farmer","n","a person who works on a farm","کشاورز","کشاورز"],
  ["fashion","n","a popular style of clothes","مد","مد"],
  ["fast","adj","moving quickly","سریع","سریع"],
  ["fasten","v","to close or attach","محکم کردن","محکم کنید"],
  ["fat","adj","having too much body weight","چاق","چاق"],
  ["father","n","a male parent","پدر","پدر"],
  ["fault","n","a mistake","اشتباه","اشتباه"],
  ["favor","n","a kind act","لطف","لطف"],
  ["favorite","adj","liked more than others","محبوب","محبوب"],
  ["fear","n","the feeling when you are afraid","ترس","ترس"],
  ["feature","n","an important part","ویژگی","ویژگی"],
  ["federal","adj","relating to a central government","فدرال","فدرال"],
  ["fee","n","money paid for a service","هزینهٔ خدمات","هزینه"],
  ["feed","v","to give food","غذا دادن","غذا دهید"],
  ["feel","v","to experience an emotion or touch","حس کردن","حس کنید"],
  ["feeling","n","an emotion","احساس","احساس"],
  ["female","adj","of the sex that can give birth","مؤنث","مؤنث"],
  ["fence","n","a barrier around land","حصار","حصار"],
  ["festival","n","a series of events for celebration","جشنواره","جشنواره"],
  ["few","det","not many","اندک","اندک"],
  ["field","n","an area of land; an area of study","میدان؛ رشته","رشته"],
  ["fight","v","to try to hurt in a struggle","جنگیدن","بجنگید"],
  ["figure","n","a number; a shape; a person","رقم؛ شکل","رقم"],
  ["file","n","a collection of papers or data","پرونده","پرونده"],
  ["fill","v","to make full","پر کردن","پر کنید"],
  ["film","n","a movie","فیلم","فیلم"],
  ["final","adj","coming at the end","نهایی","نهایی"],
  ["finally","adv","after a long time","سرانجام","سرانجام"],
  ["finance","n","the management of money","امور مالی","امور مالی"],
  ["financial","adj","relating to money","مالی","مالی"],
  ["find","v","to discover","یافتن","بیابید"],
  ["fine","adj","good; thin; a money penalty as noun","خوب؛ جریمه","خوب"],
  ["finger","n","one of the five parts of the hand","انگشت","انگشت"],
  ["finish","v","to complete","تمام کردن","تمام کنید"],
  ["fire","n","burning with flames","آتش","آتش"],
  ["firm","n","a company","شرکت","شرکت"],
  ["first","adj","coming before all others","اول","اول"],
  ["fish","n","an animal that lives in water","ماهی","ماهی"],
  ["fit","v","to be the right size","اندازه بودن","اندازه باشد"],
  ["fix","v","to repair","تعمیر کردن","تعمیر کنید"],
  ["flag","n","a piece of cloth that represents a country","پرچم","پرچم"],
  ["flame","n","the bright part of a fire","شعله","شعله"],
  ["flash","n","a sudden bright light","درخشش ناگهانی","درخشش"],
  ["flat","adj","level and smooth","صاف","صاف"],
  ["flavor","n","the taste of food","طعم","طعم"],
  ["flee","v","to run away","فرار کردن","فرار کنید"],
  ["flesh","n","the soft part of the body","گوشت","گوشت"],
  ["flight","n","a journey by air","پرواز","پرواز"],
  ["float","v","to stay on the surface of liquid","شناور بودن","شناور باشید"],
  ["flood","n","a large amount of water covering land","سیل","سیل"],
  ["floor","n","the surface you walk on in a building","کف","کف"],
  ["flour","n","powder made from grain","آرد","آرد"],
  ["flow","v","to move steadily like water","جاری شدن","جاری شود"],
  ["flower","n","the colorful part of a plant","گل","گل"],
  ["fly","v","to move through the air","پرواز کردن","پرواز کنید"],
  ["focus","v","to give attention to","تمرکز کردن","تمرکز کنید"],
  ["fold","v","to bend something over itself","تا کردن","تا کنید"],
  ["folk","n","people","مردم","مردم"],
  ["follow","v","to go after","دنبال کردن","دنبال کنید"],
  ["food","n","things that people eat","غذا","غذا"],
  ["foot","n","the part of the body you stand on","پا","پا"],
  ["football","n","a game played with a ball and goals","فوتبال","فوتبال"],
  ["for","prep","intended to belong to","برای","برای"],
  ["force","n","strength; power","نیرو","نیرو"],
  ["foreign","adj","from another country","خارجی","خارجی"],
  ["forest","n","a large area of trees","جنگل","جنگل"],
  ["forever","adv","for all time","برای همیشه","برای همیشه"],
  ["forget","v","to fail to remember","فراموش کردن","فراموش کنید"],
  ["forgive","v","to stop being angry at someone","بخشیدن","ببخشید"],
  ["form","n","a shape; a printed paper to fill in","فرم؛ شکل","فرم"],
  ["formal","adj","following official rules","رسمی","رسمی"],
  ["former","adj","from an earlier time","سابق","سابق"],
  ["formula","n","a rule written in symbols","فرمول","فرمول"],
  ["forth","adv","forward","به جلو","به جلو"],
  ["fortunate","adj","lucky","خوش‌شانس","خوش‌شانس"],
  ["fortune","n","luck; a large amount of money","بخت؛ ثروت","بخت"],
  ["forward","adv","toward the front","به جلو","به جلو"],
  ["found","v","to start an organization","بنیان نهادن","بنیان بنهید"],
  ["foundation","n","the base of a building; an organization","بنیاد","بنیاد"],
  ["frame","n","a border around a picture","قاب","قاب"],
  ["free","adj","not under control; costing nothing","آزاد؛ رایگان","آزاد"],
  ["freedom","n","the state of being free","آزادی","آزادی"],
  ["freeze","v","to become ice","یخ زدن","یخ بزند"],
  ["frequency","n","how often something happens","بسامد","بسامد"],
  ["frequent","adj","happening often","مکرر","مکرر"],
  ["fresh","adj","new; not old or tired","تازه","تازه"],
  ["friend","n","a person you like and trust","دوست","دوست"],
  ["friendly","adj","kind and pleasant","دوستانه","دوستانه"],
  ["friendship","n","the relationship between friends","دوستی","دوستی"],
  ["from","prep","starting at","از","از"],
  ["front","n","the part that faces forward","جلو","جلو"],
  ["fruit","n","the sweet part of a plant that holds seeds","میوه","میوه"],
  ["fuel","n","a substance burned for energy","سوخت","سوخت"],
  ["full","adj","holding as much as possible","پر","پر"],
  ["fun","n","enjoyment","تفریح","تفریح"],
  ["function","n","the purpose of something","کارکرد","کارکرد"],
  ["fund","n","money saved for a purpose","صندوق","صندوق"],
  ["fundamental","adj","basic and important","بنیادی","بنیادی"],
  ["funeral","n","a ceremony for a dead person","مراسم خاک‌سپاری","مراسم"],
  ["funny","adj","making you laugh","بامزه","بامزه"],
  ["furniture","n","tables, chairs, and similar objects","مبلمان","مبلمان"],
  ["further","adv","more; to a greater distance","بیشتر؛ دورتر","بیشتر"],
  ["future","n","the time after now","آینده","آینده"],
];
