/**
 * Builds src/data/daily.json and src/data/code.json — 1024 entries each.
 * Run: node scripts/gen-words.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const verbEn = [
  (w) => `They decided to ${w} before the meeting ended.`,
  (w) => `You can ${w} this with a little practice.`,
  (w) => `Please ${w} it once more so the meaning is clear.`,
  (w) => `I will ${w} as soon as the room is quiet.`,
  (w) => `We should ${w} together rather than separately.`,
];
const verbFa = [
  (w) => `آن‌ها تصمیم گرفتند پیش از پایان جلسه ${w}.`,
  (w) => `با کمی تمرین می‌توانی این را ${w}.`,
  (w) => `لطفاً یک‌بار دیگر آن را ${w} تا معنی روشن شود.`,
  (w) => `به‌محض آرام شدن اتاق، این کار را ${w}.`,
  (w) => `باید این کار را با هم ${w} نه جداگانه.`,
];
const nounEn = [
  (w) => `The ${w} changed the way we planned the day.`,
  (w) => `She kept a careful note of every ${w}.`,
  (w) => `Without a clear ${w}, the work felt unfinished.`,
  (w) => `He explained the ${w} in simple language.`,
  (w) => `This ${w} appears in everyday English all the time.`,
];
const nounFa = [
  (w) => `${w} روش برنامه‌ریزی روز را عوض کرد.`,
  (w) => `او از هر ${w} با دقت یادداشت برداشت.`,
  (w) => `بدون ${w} روشن، کار ناتمام به نظر می‌رسید.`,
  (w) => `او ${w} را با زبانی ساده توضیح داد.`,
  (w) => `این ${w} در انگلیسی روزمره زیاد دیده می‌شود.`,
];
const adjEn = [
  (w) => `It was a ${w} choice for a long journey.`,
  (w) => `The room felt ${w} after the windows opened.`,
  (w) => `Her answer was ${w} and easy to follow.`,
  (w) => `They stayed ${w} even when the plan changed.`,
  (w) => `A ${w} approach saved time later.`,
];
const adjFa = [
  (w) => `برای سفری طولانی، انتخابی ${w} بود.`,
  (w) => `پس از باز شدن پنجره‌ها، اتاق ${w} به نظر می‌رسید.`,
  (w) => `پاسخ او ${w} و قابل‌فهم بود.`,
  (w) => `حتی وقتی برنامه عوض شد، آن‌ها ${w} ماندند.`,
  (w) => `رویکردی ${w} بعداً در وقت صرفه‌جویی کرد.`,
];
const advEn = [
  (w) => `She spoke ${w} so everyone could hear.`,
  (w) => `The work was finished ${w} that afternoon.`,
  (w) => `He ${w} checked the list before leaving.`,
];
const advFa = [
  (w) => `او ${w} حرف زد تا همه بشنوند.`,
  (w) => `کار آن بعدازظهر ${w} تمام شد.`,
  (w) => `او پیش از رفتن فهرست را ${w} بررسی کرد.`,
];
const prepEn = [
  (w) => `The keys were ${w} the drawer, not on the table.`,
  (w) => `We talked ${w} the problem until midnight.`,
];
const prepFa = [
  (w) => `کلیدها ${w} کشو بودند، نه روی میز.`,
  (w) => `تا نیمه‌شب ${w} مسئله حرف زدیم.`,
];

function examples(word, pos, faHead, i) {
  if (pos === "v") {
    return { en: verbEn[i % verbEn.length](word), fa: verbFa[i % verbFa.length](faHead) };
  }
  if (pos === "adj") {
    return { en: adjEn[i % adjEn.length](word), fa: adjFa[i % adjFa.length](faHead) };
  }
  if (pos === "adv") {
    return { en: advEn[i % advEn.length](word), fa: advFa[i % advFa.length](faHead) };
  }
  if (pos === "prep" || pos === "conj") {
    return { en: prepEn[i % prepEn.length](word), fa: prepFa[i % prepFa.length](faHead) };
  }
  return { en: nounEn[i % nounEn.length](word), fa: nounFa[i % nounFa.length](faHead) };
}

function pack(rows, deck) {
  const seen = new Set();
  const out = [];
  for (const row of rows) {
    const [word, pos, defEn, defFa, faHead] = row;
    const key = word.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    const i = out.length;
    const ex = examples(word, pos, faHead || defFa, i);
    out.push({
      id: i,
      deck,
      word,
      slug: key.replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
      pos,
      en: { def: defEn, example: ex.en },
      fa: { def: defFa, example: ex.fa },
    });
  }
  return out;
}

function fillTo(rows, extras, n) {
  const copy = rows.slice();
  for (const e of extras) {
    if (copy.length >= n) break;
    copy.push(e);
  }
  if (copy.length < n) {
    throw new Error(`Need ${n}, have ${copy.length}`);
  }
  return copy.slice(0, n);
}

/** Compact tuples: word, pos, defEn, defFa, faHeadForExamples */
const dailyCore = [
  ["a","det","one; any; each","یک؛ هر","یک"],
  ["abandon","v","to leave completely","کاملاً رها کردن","رها کنند"],
  ["ability","n","the power to do something","توانایی انجام کاری","توانایی"],
  ["able","adj","having the skill to do something","توانا؛ قادر","توانا"],
  ["about","prep","on the subject of","دربارهٔ","دربارهٔ"],
  ["above","prep","at a higher place than","بالای","بالای"],
  ["abroad","adv","in another country","در خارج از کشور","در خارج"],
  ["absent","adj","not present","غایب","غایب"],
  ["accept","v","to take something offered","پذیرفتن","بپذیرید"],
  ["access","n","a way of entering or using","دسترسی","دسترسی"],
  ["accident","n","an unexpected harmful event","حادثه","حادثه"],
  ["accompany","v","to go with someone","همراهی کردن","همراهی کنید"],
  ["according","prep","as stated by","طبق؛ بنا بر","طبق"],
  ["account","n","a record of money or a story","حساب؛ شرح","حساب"],
  ["accurate","adj","correct and exact","دقیق","دقیق"],
  ["achieve","v","to succeed in doing something","موفق شدن به انجام","انجام دهید"],
  ["across","prep","from one side to the other","از عرض؛ آن‌سوی","از عرض"],
  ["act","v","to do something; to perform","عمل کردن؛ بازی کردن","عمل کنید"],
  ["action","n","the process of doing","عمل","عمل"],
  ["active","adj","doing things; energetic","فعال","فعال"],
  ["activity","n","something you do","فعالیت","فعالیت"],
  ["actor","n","a person who performs in plays or films","بازیگر","بازیگر"],
  ["actual","adj","real, not imagined","واقعی","واقعی"],
  ["actually","adv","in fact","در واقع","در واقع"],
  ["ad","n","a paid public notice","آگهی","آگهی"],
  ["adapt","v","to change to fit a new situation","سازگار شدن","سازگار شوید"],
  ["add","v","to put together with something else","اضافه کردن","اضافه کنید"],
  ["addition","n","the act of adding","اضافه کردن؛ جمع","اضافه"],
  ["address","n","the details of a place","نشانی","نشانی"],
  ["admire","v","to respect and like","تحسین کردن","تحسین کنید"],
  ["admit","v","to agree that something is true","اعتراف کردن","اعتراف کنید"],
  ["adult","n","a fully grown person","بزرگسال","بزرگسال"],
  ["advance","v","to move forward","پیش رفتن","پیش بروید"],
  ["advantage","n","something that helps you","مزیت","مزیت"],
  ["adventure","n","an exciting experience","ماجراجویی","ماجراجویی"],
  ["advertisement","n","a public notice to sell something","آگهی تبلیغاتی","آگهی"],
  ["advice","n","an opinion about what to do","مشاوره؛ اندرز","اندرز"],
  ["advise","v","to give advice","توصیه کردن","توصیه کنید"],
  ["affair","n","an event or matter","امر؛ ماجرا","ماجرا"],
  ["affect","v","to influence","تأثیر گذاشتن بر","تأثیر بگذارید"],
  ["afford","v","to have enough money for","از عهده برآمدن","از عهده بربیایید"],
  ["afraid","adj","feeling fear","ترسیده","ترسیده"],
  ["after","prep","later than","بعد از","بعد از"],
  ["afternoon","n","the time after midday","بعدازظهر","بعدازظهر"],
  ["afterward","adv","later","بعداً","بعداً"],
  ["again","adv","one more time","دوباره","دوباره"],
  ["against","prep","in opposition to","علیه؛ در برابر","در برابر"],
  ["age","n","how old someone is","سن","سن"],
  ["agency","n","a business that provides a service","آژانس","آژانس"],
  ["agent","n","someone who acts for another","نماینده","نماینده"],
  ["ago","adv","in the past","پیش","پیش"],
  ["agree","v","to have the same opinion","موافق بودن","موافق باشید"],
  ["agreement","n","a shared decision","توافق","توافق"],
  ["ahead","adv","in front","جلو","جلو"],
  ["aid","n","help","کمک","کمک"],
  ["aim","n","a purpose","هدف","هدف"],
  ["air","n","the gas we breathe","هوا","هوا"],
  ["airline","n","a company that flies planes","شرکت هواپیمایی","شرکت هواپیمایی"],
  ["airport","n","a place where planes take off","فرودگاه","فرودگاه"],
  ["alarm","n","a warning sound","هشدار","هشدار"],
  ["album","n","a collection of songs or photos","آلبوم","آلبوم"],
  ["alcohol","n","a drink that can make you drunk","الکل","الکل"],
  ["alive","adj","living","زنده","زنده"],
  ["all","det","the whole number of","همه","همه"],
  ["allow","v","to permit","اجازه دادن","اجازه دهید"],
  ["almost","adv","nearly","تقریباً","تقریباً"],
  ["alone","adj","without other people","تنها","تنها"],
  ["along","prep","from one end to the other of","در امتداد","در امتداد"],
  ["already","adv","before now","از قبل","از قبل"],
  ["also","adv","in addition","همچنین","همچنین"],
  ["alter","v","to change","تغییر دادن","تغییر دهید"],
  ["alternative","n","another choice","گزینهٔ جایگزین","گزینه"],
  ["although","conj","despite the fact that","اگرچه","اگرچه"],
  ["always","adv","at all times","همیشه","همیشه"],
  ["amaze","v","to surprise greatly","شگفت‌زده کردن","شگفت‌زده کنید"],
  ["amazing","adj","causing great surprise","شگفت‌انگیز","شگفت‌انگیز"],
  ["ambition","n","a strong wish to succeed","جاه‌طلبی؛ آرمان","آرمان"],
  ["among","prep","in the middle of","در میان","در میان"],
  ["amount","n","a quantity","مقدار","مقدار"],
  ["amuse","v","to make someone laugh","سرگرم کردن","سرگرم کنید"],
  ["analysis","n","a detailed study","تحلیل","تحلیل"],
  ["ancient","adj","very old","باستانی","باستانی"],
  ["and","conj","also; plus","و","و"],
  ["anger","n","a strong feeling of being upset","خشم","خشم"],
  ["angle","n","the space between two lines","زاویه","زاویه"],
  ["angry","adj","feeling anger","عصبانی","عصبانی"],
  ["animal","n","a living creature that is not a plant","حیوان","حیوان"],
  ["announce","v","to tell people publicly","اعلام کردن","اعلام کنید"],
  ["annoy","v","to make someone a little angry","آزار دادن","آزار دهید"],
  ["annual","adj","happening once a year","سالانه","سالانه"],
  ["another","det","one more","یکی دیگر","یکی دیگر"],
  ["answer","n","a reply","پاسخ","پاسخ"],
  ["anxiety","n","a feeling of worry","اضطراب","اضطراب"],
  ["anxious","adj","worried","نگران","نگران"],
  ["any","det","one, some, or every","هر؛ هیچ","هر"],
  ["anybody","n","any person","هر کسی","هر کسی"],
  ["anymore","adv","any longer","دیگر","دیگر"],
  ["anyone","n","any person","هر کس","هر کس"],
  ["anything","n","any thing","هر چیز","هر چیز"],
  ["anyway","adv","in any case","به هر حال","به هر حال"],
  ["anywhere","adv","in any place","هر جا","هر جا"],
  ["apart","adv","separated","جدا","جدا"],
  ["apartment","n","a set of rooms to live in","آپارتمان","آپارتمان"],
  ["apologize","v","to say you are sorry","عذرخواهی کردن","عذرخواهی کنید"],
  ["apparent","adj","easy to see","آشکار","آشکار"],
  ["appear","v","to become visible","ظاهر شدن","ظاهر شوید"],
  ["appearance","n","the way someone looks","ظاهر","ظاهر"],
  ["apple","n","a round fruit","سیب","سیب"],
  ["application","n","a formal request; a software program","درخواست؛ برنامه","درخواست"],
  ["apply","v","to make a formal request","درخواست دادن","درخواست دهید"],
  ["appoint","v","to choose someone for a job","منصوب کردن","منصوب کنید"],
  ["appointment","n","an arranged meeting","قرار ملاقات","قرار"],
  ["appreciate","v","to be grateful for","قدردانی کردن","قدردانی کنید"],
  ["approach","v","to come near","نزدیک شدن","نزدیک شوید"],
  ["appropriate","adj","suitable","مناسب","مناسب"],
  ["approval","n","agreement that something is good","تأیید","تأیید"],
  ["approve","v","to agree officially","تصویب کردن","تصویب کنید"],
  ["approximately","adv","about; not exact","تقریباً","تقریباً"],
  ["architect","n","a person who designs buildings","معمار","معمار"],
  ["area","n","a region or surface","منطقه؛ مساحت","منطقه"],
  ["argue","v","to give reasons; to disagree","بحث کردن","بحث کنید"],
  ["argument","n","a disagreement; a reason","بحث؛ استدلال","استدلال"],
  ["arise","v","to happen; to stand up","پیش آمدن","پیش بیاید"],
  ["arm","n","the body part from shoulder to hand","بازو","بازو"],
  ["army","n","a large group of soldiers","ارتش","ارتش"],
  ["around","prep","on all sides of","دورِ","دورِ"],
  ["arrange","v","to plan or put in order","مرتب کردن؛ ترتیب دادن","ترتیب دهید"],
  ["arrangement","n","a plan","ترتیب","ترتیب"],
  ["arrest","v","to take someone to the police","دستگیر کردن","دستگیر کنید"],
  ["arrival","n","the act of arriving","ورود","ورود"],
  ["arrive","v","to reach a place","رسیدن","برسید"],
  ["art","n","creative work such as painting","هنر","هنر"],
  ["article","n","a piece of writing; a thing","مقاله؛ کالا","مقاله"],
  ["artist","n","a person who creates art","هنرمند","هنرمند"],
  ["as","conj","because; while; in the way that","چون؛ همان‌طور که","همان‌طور که"],
  ["ashamed","adj","feeling shame","شرمنده","شرمنده"],
  ["aside","adv","to one side","کنار","کنار"],
  ["ask","v","to put a question","پرسیدن","بپرسید"],
  ["asleep","adj","sleeping","خواب","خواب"],
  ["aspect","n","one part of a situation","جنبه","جنبه"],
  ["assault","n","a violent attack","حمله","حمله"],
  ["assembly","n","a gathering of people","مجمع","مجمع"],
  ["assess","v","to judge the quality of","ارزیابی کردن","ارزیابی کنید"],
  ["asset","n","something valuable","دارایی","دارایی"],
  ["assign","v","to give a task","محول کردن","محول کنید"],
  ["assist","v","to help","کمک کردن","کمک کنید"],
  ["assistant","n","a person who helps","دستیار","دستیار"],
  ["associate","v","to connect in the mind","مرتبط دانستن","مرتبط بدانید"],
  ["association","n","a group of people with a shared purpose","انجمن","انجمن"],
  ["assume","v","to accept as true without proof","فرض کردن","فرض کنید"],
  ["assure","v","to tell someone firmly","اطمینان دادن","اطمینان دهید"],
  ["at","prep","in a place or time","در؛ نزد","در"],
  ["athlete","n","a person who plays sport","ورزشکار","ورزشکار"],
  ["atmosphere","n","the air; the mood of a place","جو؛ فضا","فضا"],
  ["attach","v","to join","ضمیمه کردن","ضمیمه کنید"],
  ["attack","v","to try to hurt","حمله کردن","حمله کنید"],
  ["attempt","n","a try","تلاش","تلاش"],
  ["attend","v","to be present at","حضور یافتن در","حضور یابید"],
  ["attention","n","careful notice","توجه","توجه"],
  ["attitude","n","a way of thinking","نگرش","نگرش"],
  ["attract","v","to pull toward","جذب کردن","جذب کنید"],
  ["attractive","adj","pleasant to look at","جذاب","جذاب"],
  ["audience","n","people watching or listening","مخاطب","مخاطب"],
  ["aunt","n","the sister of a parent","عمه یا خاله","عمه یا خاله"],
  ["author","n","a writer","نویسنده","نویسنده"],
  ["authority","n","the power to give orders","اقتدار","اقتدار"],
  ["automatic","adj","working by itself","خودکار","خودکار"],
  ["available","adj","able to be used","در دسترس","در دسترس"],
  ["average","n","the typical amount","میانگین","میانگین"],
  ["avoid","v","to stay away from","اجتناب کردن از","اجتناب کنید"],
  ["awake","adj","not sleeping","بیدار","بیدار"],
  ["award","n","a prize","جایزه","جایزه"],
  ["aware","adj","knowing about something","آگاه","آگاه"],
  ["away","adv","to another place","دور","دور"],
  ["awful","adj","very bad","وحشتناک","وحشتناک"],
  ["baby","n","a very young child","نوزاد","نوزاد"],
  ["back","n","the rear part","پشت","پشت"],
  ["background","n","the setting behind something","پس‌زمینه","پس‌زمینه"],
  ["backup","n","an extra copy or support","نسخهٔ پشتیبان","پشتیبان"],
  ["backwards","adv","toward the back","به عقب","به عقب"],
  ["bacteria","n","tiny living organisms","باکتری","باکتری"],
  ["bad","adj","not good","بد","بد"],
  ["bag","n","a container you carry","کیسه؛ کیف","کیف"],
  ["bake","v","to cook in an oven","پختن در فر","بپزید"],
  ["balance","n","a state of equal weight","تعادل","تعادل"],
  ["ball","n","a round object used in games","توپ","توپ"],
  ["ban","v","to forbid","ممنوع کردن","ممنوع کنید"],
  ["band","n","a group of musicians","گروه موسیقی","گروه"],
  ["bank","n","a place that keeps money","بانک","بانک"],
  ["bar","n","a place that serves drinks; a long piece","بار؛ میله","میله"],
  ["bare","adj","without covering","لخت؛ برهنه","برهنه"],
  ["bargain","n","something bought cheaply","معاملهٔ خوب","معامله"],
  ["barrier","n","something that blocks","مانع","مانع"],
  ["base","n","the bottom or starting point","پایه","پایه"],
  ["basic","adj","simple and necessary","اساسی","اساسی"],
  ["basis","n","the reason or foundation","مبنای","مبنا"],
  ["basket","n","a container made of woven material","سبد","سبد"],
  ["bath","n","washing the body in a tub","حمام","حمام"],
  ["bathroom","n","a room with a toilet and sink","دستشویی","دستشویی"],
  ["battery","n","a device that stores electricity","باتری","باتری"],
  ["battle","n","a fight between armies","نبرد","نبرد"],
  ["be","v","to exist; to have a quality","بودن","باشید"],
  ["beach","n","sand beside the sea","ساحل","ساحل"],
  ["bean","n","a seed used as food","لوبیا","لوبیا"],
  ["bear","v","to carry; to accept","تحمل کردن","تحمل کنید"],
  ["beard","n","hair on the chin","ریش","ریش"],
  ["beat","v","to hit repeatedly; to win against","زدن؛ شکست دادن","بزنید"],
  ["beautiful","adj","very pleasing to see","زیبا","زیبا"],
  ["because","conj","for the reason that","چون","چون"],
  ["become","v","to start to be","شدن","بشوید"],
  ["bed","n","furniture for sleeping","تخت","تخت"],
  ["bedroom","n","a room for sleeping","اتاق خواب","اتاق خواب"],
  ["bee","n","an insect that makes honey","زنبور عسل","زنبور"],
  ["beef","n","meat from a cow","گوشت گاو","گوشت گاو"],
  ["beer","n","an alcoholic drink made from grain","آبجو","آبجو"],
  ["before","prep","earlier than","قبل از","قبل از"],
  ["begin","v","to start","شروع کردن","شروع کنید"],
  ["beginning","n","the first part","آغاز","آغاز"],
  ["behave","v","to act in a certain way","رفتار کردن","رفتار کنید"],
  ["behavior","n","the way someone acts","رفتار","رفتار"],
  ["behind","prep","at the back of","پشتِ","پشتِ"],
  ["being","n","existence; a living thing","وجود؛ موجود","وجود"],
  ["belief","n","something you think is true","باور","باور"],
  ["believe","v","to think something is true","باور کردن","باور کنید"],
  ["bell","n","an object that makes a ringing sound","زنگ","زنگ"],
  ["belong","v","to be owned by","متعلق بودن","متعلق باشد"],
  ["below","prep","in a lower place than","زیرِ","زیرِ"],
  ["belt","n","a strip worn around the waist","کمربند","کمربند"],
  ["bench","n","a long seat","نیمکت","نیمکت"],
  ["bend","v","to curve","خم کردن","خم کنید"],
  ["benefit","n","a good result","فایده","فایده"],
  ["beside","prep","next to","کنارِ","کنارِ"],
  ["besides","prep","in addition to","علاوه بر","علاوه بر"],
  ["best","adj","better than all others","بهترین","بهترین"],
  ["bet","v","to risk money on a result","شرط بستن","شرط ببندید"],
  ["better","adj","of a higher quality","بهتر","بهتر"],
  ["between","prep","in the space separating","بین","بین"],
  ["beyond","prep","on the far side of","فراتر از","فراتر از"],
  ["bicycle","n","a two-wheeled vehicle you pedal","دوچرخه","دوچرخه"],
  ["bid","n","an offer of a price","پیشنهاد قیمت","پیشنهاد"],
  ["big","adj","large","بزرگ","بزرگ"],
  ["bike","n","a bicycle","دوچرخه","دوچرخه"],
  ["bill","n","a request for payment","صورت‌حساب","صورت‌حساب"],
  ["bin","n","a container for rubbish","سطل زباله","سطل"],
  ["bind","v","to tie","بستن","ببندید"],
  ["biology","n","the study of living things","زیست‌شناسی","زیست‌شناسی"],
  ["bird","n","an animal with feathers and wings","پرنده","پرنده"],
  ["birth","n","the moment of being born","تولد","تولد"],
  ["birthday","n","the date someone was born","زادروز","زادروز"],
  ["bit","n","a small piece","ذره؛ کمی","ذره"],
  ["bite","v","to cut with the teeth","گاز گرفتن","گاز بگیرید"],
  ["bitter","adj","having a sharp taste; angry","تلخ","تلخ"],
  ["black","adj","the darkest color","سیاه","سیاه"],
  ["blade","n","the flat cutting part","تیغه","تیغه"],
  ["blame","v","to say someone caused a problem","سرزنش کردن","سرزنش کنید"],
  ["blank","adj","empty; with no writing","خالی؛ سفید","خالی"],
  ["blind","adj","unable to see","نابینا","نابینا"],
  ["block","n","a solid piece; a group of buildings","بلوک؛ قطعه","بلوک"],
  ["blood","n","the red liquid in the body","خون","خون"],
  ["blow","v","to send out air","دمیدن","بدمید"],
  ["blue","adj","the color of a clear sky","آبی","آبی"],
  ["board","n","a flat piece of wood; a group of directors","تخته؛ هیئت","تخته"],
  ["boat","n","a small vehicle that travels on water","قایق","قایق"],
  ["body","n","the physical structure of a person","بدن","بدن"],
  ["boil","v","to heat until bubbling","جوشاندن","جوشانید"],
  ["bomb","n","a weapon that explodes","بمب","بمب"],
  ["bond","n","a close connection","پیوند","پیوند"],
  ["bone","n","a hard part of the skeleton","استخوان","استخوان"],
  ["book","n","pages bound together to read","کتاب","کتاب"],
  ["boom","n","a sudden increase","رونق ناگهانی","رونق"],
  ["boost","v","to increase","افزایش دادن","افزایش دهید"],
  ["boot","n","a strong shoe that covers the ankle","چکمه","چکمه"],
  ["border","n","the line between two countries","مرز","مرز"],
  ["bore","v","to make someone uninterested","خسته کردن","خسته کنید"],
  ["born","adj","brought into life","متولدشده","متولدشده"],
  ["borrow","v","to take for a time and return","قرض گرفتن","قرض بگیرید"],
  ["boss","n","a person in charge","رئیس","رئیس"],
  ["both","det","the two","هر دو","هر دو"],
  ["bother","v","to disturb","زحمت دادن","زحمت دهید"],
  ["bottle","n","a container for liquid","بطری","بطری"],
  ["bottom","n","the lowest part","پایین","پایین"],
  ["bound","adj","certain; tied","مجبور؛ بسته","مجبور"],
  ["boundary","n","a dividing line","مرز","مرز"],
  ["bowl","n","a round deep dish","کاسه","کاسه"],
  ["box","n","a container with sides","جعبه","جعبه"],
  ["boy","n","a male child","پسر","پسر"],
  ["boyfriend","n","a male romantic partner","دوست‌پسر","دوست‌پسر"],
  ["brain","n","the organ inside the head","مغز","مغز"],
  ["branch","n","a part of a tree; a local office","شاخه؛ شعبه","شاخه"],
  ["brand","n","a product name","نام تجاری","نام تجاری"],
  ["brave","adj","ready to face danger","شجاع","شجاع"],
  ["bread","n","a baked food made from flour","نان","نان"],
  ["break","v","to separate into pieces","شکستن","بشکنید"],
  ["breakfast","n","the first meal of the day","صبحانه","صبحانه"],
  ["breast","n","the chest; a mammary gland","سینه","سینه"],
  ["breath","n","air taken into the lungs","نفس","نفس"],
  ["breathe","v","to take air in and out","نفس کشیدن","نفس بکشید"],
  ["breed","v","to produce young","پرورش دادن","پرورش دهید"],
  ["brick","n","a block used to build walls","آجر","آجر"],
  ["bridge","n","a structure over a river or road","پل","پل"],
  ["brief","adj","short in time","کوتاه","کوتاه"],
  ["bright","adj","giving a lot of light","روشن","روشن"],
  ["brilliant","adj","very clever; very bright","درخشان؛ نابغه","درخشان"],
  ["bring","v","to take something with you to a place","آوردن","بیاورید"],
  ["broad","adj","wide","پهن","پهن"],
  ["broadcast","v","to send out on radio or TV","پخش کردن","پخش کنید"],
  ["brother","n","a male sibling","برادر","برادر"],
  ["brown","adj","the color of chocolate","قهوه‌ای","قهوه‌ای"],
  ["brush","n","a tool with bristles","برس","برس"],
  ["bubble","n","a ball of air in liquid","حباب","حباب"],
  ["budget","n","a plan for spending money","بودجه","بودجه"],
  ["build","v","to make a structure","ساختن","بسازید"],
  ["building","n","a structure with a roof","ساختمان","ساختمان"],
  ["bullet","n","a small object fired from a gun","گلوله","گلوله"],
  ["bunch","n","a group of things together","دسته","دسته"],
  ["burden","n","a heavy load or worry","بار؛ مسئولیت سنگین","بار"],
  ["burn","v","to be on fire","سوختن","بسوزد"],
  ["burst","v","to break open suddenly","ترکیدن","بترکد"],
  ["bury","v","to put under the ground","دفن کردن","دفن کنید"],
  ["bus","n","a large road vehicle for passengers","اتوبوس","اتوبوس"],
  ["business","n","work that makes money","کسب‌وکار","کسب‌وکار"],
  ["busy","adj","having a lot to do","مشغول","مشغول"],
  ["but","conj","however","اما","اما"],
  ["butter","n","a yellow food made from cream","کره","کره"],
  ["button","n","a small disc for fastening clothes","دکمه","دکمه"],
  ["buy","v","to get something by paying","خریدن","بخرید"],
  ["buyer","n","a person who buys","خریدار","خریدار"],
  ["by","prep","next to; through the work of","به‌وسیلهٔ؛ کنار","به‌وسیلهٔ"],
];

export { dailyCore, examples, pack, fillTo, verbEn };
